### ISSUE TITLE
系列IDE插件: 英汉词典与衍生项目

### ISSUE THREAD

**Issue by nobodxbodon** [program-in-chinese/overview#104]
在https://github.com/program-in-chinese/overview/issues/86 的不同方向探索过程中(在线服务, 浏览器插件, IDE插件), 最近的[vscode英汉词典插件](https://zhuanlan.zhihu.com/p/48791726)较有需求, 一周安装数已超300, 估计月内可以破千. 

[打算](https://zhuanlan.zhihu.com/p/49133480)用TypeScript重构, 并在此基础上开发[vscode中的代码翻译预览功能](https://github.com/program-in-chinese/overview/issues/86#issuecomment-436745681). @htwx @lightrabbit 或任何其他有兴趣的成员欢迎参与. 另外想咨询一下如何实现插件间调用.

另外, 考虑在其他IDE中实现类似功能, 如Visual Studio, Eclipse(应该是Java实现), IntelliJ IDEA等.

**Comment by nobodxbodon** [comment]
在v2做了调研发现[JetBrains的需求比较大](https://www.v2ex.com/t/507615)
@ice1000 看到你已经做了[同类插件](https://github.com/ice1000/A8Translate), 但也有在线翻译API的次数限制. 不知有没有兴趣改用基于这个离线词典数据实现?

**Comment by absente** [comment]
merge <- https://github.com/program-in-chinese/overview/issues/88

**Comment by nobodxbodon** [comment]
待有用户反馈再开.
