### ISSUE TITLE
建了一个MSTeam，方便即时交流

### ISSUE THREAD

**Issue by absente** [program-in-chinese/overview#105]
微信群没有分组等功能，不够方便，gitter/slack访问不够稳定，目前来看，MSTeam是最合适的：
https://teams.microsoft.com/l/team/19%3aebfd10b3245543aea2859aff7b9ab4f4%40thread.skype/conversations?groupId=962607ad-4f24-46fd-802a-2348822de965&tenantId=92246c25-ecbf-47fe-b266-8e0257b25a8d

**Comment by zaoqi-unsafe** [comment]
telegram可能更好

**Comment by absente** [comment]
暂且用qq+wx替代，此方案留作备选。 群，620225373
