### ISSUE TITLE
Halting Problem

### ISSUE THREAD

**Issue by zaoqi-unsafe** [program-in-chinese/overview#106]
我避免了这个问题,但产生的问题难以解决。
昨日我描述为(miniKanre/run*o q (evalo env code q) '())

**Comment by nobodxbodon** [comment]
停机问题历史悠久. 相关论文也是汗牛充栋. 如有参考请分享一下出处? 或者尽量用中文详述你的思路?

**Comment by zaoqi-unsafe** [comment]
允许分步地把算不出值的东西替换为错误。替换的算法还没有，可能用一个自动的proof prover或proof sarcher可以解决。
这会导致结果可以有很多种，等能被接受的矛盾。

**Comment by zaoqi-unsafe** [comment]
这是zaoqi的unsafe账号。我不只为了中文而实现一些语言。

**Comment by nobodxbodon** [comment]
> 允许分步地把算不出值的东西替换为错误

如何判断是“算不出值”还只是需要花太长时间？

**Comment by bctnry** [comment]
停机问题不可解，这是已经被证明了的。

**Comment by zaoqi** [comment]
我我知道。我说"避免",不是解决

**Comment by zaoqi** [comment]
> > 允许分步地把算不出值的东西替换为错误
> 
> 如何判断是“算不出值”还只是需要花太长时间？

可能可以尝试证明某个东西eval会后不能是任何值。

**Comment by zaoqi** [comment]
避免这个问题会改变语言的定义。这个问题确实是不能解决，但好像能避免。
