### ISSUE TITLE
网

### ISSUE THREAD

**Issue by zaoqi-unsafe** [program-in-chinese/overview#108]
我设计了一个不需要English的网等东西。
不可封是一个目标

**Comment by zaoqi-unsafe** [comment]
设计使用寿命较短，所以用RSA。
RSA公钥作为地址，取消端口。暂时将被实现在有或无IP封锁的有或无公网IP的采用IPv4的网络上。分布式的储存地址的表。要求一部分客户端有公网IPv4并且网络没有被一些机构完全的封锁为多个部分使这个网络能运行。如果穷，可以在一些免费的各种地方的PHP服务器上搭建一些用来转发的东西。

**Comment by bctnry** [comment]
已经有了。https://github.com/HelloZeroNet/ZeroNet

**Comment by zaoqi-unsafe** [comment]
网不是网站

**Comment by zaoqi-unsafe** [comment]
超级长的经常更新的mass的English底层代码有必要重写。

**Comment by bctnry** [comment]
结论就是，你搞出来的东西还是要做在IP之上，然后你还是会遇到地址表太××长的问题，然后你还是要为了解决这个问题把地址表outsource给专门的设备。BOOM，你又发明了一遍路由器。RSA公钥太长记不住怎么办？引入一套别名+别名解析的机制。BOOM，你又把现在的DNS的那一套发明了一遍。不搞别名了，直接交换公钥吧！那又要怎么交换公钥？怎么在交换公钥的时候避免中间人攻击？BOOM，你又把HTTPS发明了一遍，而且可能还没有别人想得那样周到。还是想做？来来来，FreeNet，ZeroNet，Solid，Tox，Bitmessage，随你挑随你选。

在这里叫着不要English不要English有用吗？你不如还是乖乖上学罢。

**Comment by absente** [comment]
@ZoomQuiet 怎样造轮子才算不无聊？现在这么多脚本语言，是不是都无聊至极的玩物？

**Comment by nobodxbodon** [comment]
个人认为, 造轮子要视其目的. 毕竟真轮子造了几千年还在各种技术进步/创新.
如果是技术上有所区别, 一开始就加以说明为好. 如果是基于某种现有理论/协议重新实现以在实践中学习, 最好说明基于的对象. 如果与 https://github.com/program-in-chinese/overview/issues/107 目的相似, 不妨在那里提出具体项目.
无论如何, 支持动手实践.
