### ISSUE TITLE
基于中文逻辑重构/扩展chromium

### ISSUE THREAD

**Issue by absente** [program-in-chinese/overview#110]
定以`Vivaldi2.0`为蓝本，https://github.com/secti6n/v2/issues

代码量很大，所以是个长期项目

**Comment by nobodxbodon** [comment]
与https://github.com/program-in-chinese/overview/issues/109 类似, 建议先在https://github.com/program-in-chinese/overview/issues/107 调研. 如有具体计划和实行, 再开单独issue. 也适用于其他大量潜在项目.

**Comment by absente** [comment]
@nobodxbodon 个人已经调研过了，具体的内容会后续补充上来。具体的计划目前正在整理

**Comment by absente** [comment]
hide
