### ISSUE TITLE
实现基于中文编程的REPL

### ISSUE THREAD

**Issue by absente** [program-in-chinese/overview#111]
仓库：https://github.com/program-in-chinese/c8
命名：竹
主页：github.com/z75
实现：typescript，erlang，python3
群：493643262

**Comment by absente** [comment]
ref: https://github.com/program-in-chinese/overview/issues/61 通过浏览器插件实现一个计算/编程工具

**Comment by nobodxbodon** [comment]
https://github.com/program-in-chinese/overview/issues/113 组会中有不少介绍, 感觉能够全力投入一段时间非常不容易. 一点个人想法:

可否先用最短时间做一个最小规模的原型? 如果没有完整详细设计, 也许最好用短周期快迭代来留出试错的缓冲.
比如首先只针对一个后端语言, 实现核心中文语法/功能, 其他外部库可以暂缓. 
以5-6个月的总时间来算, 第一个迭代(完成上面目标)最好在1-2月, 第二个迭代做一些设计改进和文档化2个月左右, 最后还可以做第三个迭代重构+完善(外部库等等)1-2个月. 当然方便的话迭代可以更短.

**Comment by absente** [comment]
我先低调一点，把这个关了
