### ISSUE TITLE
2018年12月8日 语音组会

### ISSUE THREAD

**Issue by nobodxbodon** [program-in-chinese/overview#114]
@program-in-chinese/all 组内微信群加入方式见 https://github.com/program-in-chinese/overview/issues/66#issuecomment-443151418
组会形式与备用qq群信息见 https://github.com/program-in-chinese/overview/issues/113#issuecomment-443457875 请尽量提前占楼(在此issue添加comment), 对在会中想要讨论/分享的内容作提纲/简介.
暂定仍在北京时间周六14:00开始, 请尽量准时.

**Comment by nobodxbodon** [comment]
🛋 下周打算做的:
- "英汉词典"插件[改进](https://github.com/program-in-chinese/vscode_english_chinese_dictionary/issues/12)
- [Scala笔记](https://github.com/program-in-chinese/Programming_in_Scala_study_notes_zh)新添一章

**Comment by absente** [comment]
merge,ref #114

**Comment by nobodxbodon** [comment]
与 @cflw 交流了一些组内正在进行的项目, 对个人手头的两个想法 ( https://github.com/program-in-chinese/overview/issues/104 和 https://github.com/program-in-chinese/overview/issues/97 )有了更多动力和启发.
也对推广进行了探讨, 之前的 https://github.com/program-in-chinese/overview/issues/70 需要继续探索, 包括社区如csdn, 微信公众号等等.

@program-in-chinese/all 打算下次直接在qq群开会, 也尝试开放组外人员参与. 有兴趣的请加群: 620225373

**Comment by absente** [comment]
ref/back-link:
2018年12月8日 第二次\语音组会 #114
