### ISSUE TITLE
基于光通信的平衡三进制非进位的符号系统的设计实现

### ISSUE THREAD

**Issue by absente** [program-in-chinese/overview#115]

**Comment by absente** [comment]
这个坑很大，但是，不是纯虚无概念。俄罗斯做出过基于电信号的balanced-ternary computer，我的想法类似，但是通过光信号，以及对光信号传输的模拟、光的偏振来实现。也就说，可以有办法实现逻辑光通路，而不需要借助，逻辑门电路。

**Comment by absente** [comment]
其实是ref #111 的

**Comment by absente** [comment]
暂时先不再更新细节，先刮起

**Comment by RubyLouvre** [comment]
中国古人的数学好垃圾的，不知为什么要扯上去

**Comment by absente** [comment]
不存在的哦。中国古代是算术一般，术数领先。术数相当于古典数论。我不是要扯上，而是从中理解到了。正如二进制也是莱布尼兹从阴阳理论的出来的。当然，冯诺依曼做的事情，主要是把[二进位制]的存储传输体系确立了。 @RubyLouvre

**Comment by absente** [comment]
另外，如何解决进制兼容和`离散特征化`的问题，很简单，通过可见光和非可见光的波长实现先。比如，gif有256色RGB，那么相当于，已经可以推广到255进制。同样的，为了方便存储，可以使用255-360-1080进制，而非3进制。

最后，为了方便推广，我会去联络九三学社、社科院、外研社、中科院物理研究所的人，不要问我怎么联系到的，我会去做就是了。

**Comment by absente** [comment]
bookmark/收集
http://homepage.divms.uiowa.edu/~jones/ternary/logic.shtml

**Comment by absente** [comment]
聊天记录merge/选摘

【APUE】Narc(544310440) 2018/12/8 20:38:11
那图里不是说四原色吗
【TLDP】東491(735151965)  10:43:00
 对，黄和绿是叠加态，属于量子位

**Comment by absente** [comment]
我记得昨天有人问我要三进制电路逻辑门来着

【i16】萌新(184858399) 9:57:53http://homepage.divms.uiowa.edu/~jones/ternary/logic.shtml
--
【i16】萌新(184858399) 9:57:58我要的是这种
【u8】東491(735151965) 10:04:09@萌新 这个也有，不过是俄文的
【u8】東491(735151965) 10:04:13等我总结完再说

【RBQ要造反】h_ang!(J2, 7);<huangjj.27@qq.com> 10:05:55我想说 三进制的信息密度优势 在今天根本不是优势
--
【u8】東491(735151965) 10:06:03呵呵
【u8】東491(735151965) 10:06:08nice point
【u8】東491(735151965) 10:06:10我记下了
【u8】東491(735151965) 10:06:15感谢分享
【RBQ要造反】h_ang!(J2, 7);<huangjj.27@qq.com> 10:06:22同时 也会造成电路设计更加复杂
【u8】東491(735151965) 10:06:39其实我们真正在用的不是ternary，而是base1080 on ternary
【u8】東491(735151965) 10:07:01@h_ang!(J2, 7); AWWBWG，我们不收hold不住复杂度的低级工程师
【RBQ要造反】h_ang!(J2, 7);<huangjj.27@qq.com> 10:07:01@東491 解释一下分别是什么？
【u8】東491(735151965) 10:07:37我没有这个义务，我是二炮出来的，有些东西涉密，在不知道你有没有境外背景之前，恕难从命
【RBQ要造反】h_ang!(J2, 7);<huangjj.27@qq.com> 10:07:43 老板：？？？不给我省钱是吧？ 炒了
【RBQ要造反】h_ang!(J2, 7);<huangjj.27@qq.com> 10:08:24@東491 如果你说军工 会在乎钱？  三进制搞起搞起
【u8】東491(735151965) 10:08:48@h_ang!(J2, 7); 对的
【u8】東491(735151965) 10:08:59我们旅，钱很多
【RBQ要造反】h_ang!(J2, 7);<huangjj.27@qq.com> 10:09:01我只是说 一般民用呀 商业推广 在现在的市场根本做不了
【u8】東491(735151965) 10:09:11民用 等2025吧
【RBQ要造反】h_ang!(J2, 7);<huangjj.27@qq.com> 10:09:19纳税人：？？？
【u128】智商药水(737445366) 10:09:20
【u8】東491(735151965) 10:09:20可以稍稍期待一下
【u8】東491(735151965) 10:09:46@h_ang!(J2, 7); 建议更换国籍
【i16】萌新(184858399) 10:10:21
【i16】萌新(184858399) 10:10:29你这说一半又不说
【i16】萌新(184858399) 10:10:40真的让人很难受
【RBQ要造反】h_ang!(J2, 7);<huangjj.27@qq.com> 10:11:09@東491 什么鬼？？？
【u8】東491(735151965) 10:11:15@h_ang!(J2, 7); 靠，我想说啊
【u8】東491(735151965) 10:11:21有协议
【i16】萌新(184858399) 10:11:22穿山甲到底说了什么
【u8】東491(735151965) 10:11:36妈蛋被国安发现，我就真的要去喝茶了
【i16】萌新(184858399) 10:11:48国安
【RBQ要造反】h_ang!(J2, 7);<huangjj.27@qq.com> 10:11:52我只是表示 我作为一个纳税人 我完全懵了而已呀…… 结果你就让我换国籍
【u8】東491(735151965) 10:12:01我虽然已经离队了，但是名单是永久的，我被实时监听
【i16】萌新(184858399) 10:12:01足球队
【i16】萌新(184858399) 10:12:10国安撒比
【u8】東491(735151965) 10:12:14@h_ang!(J2, 7); 不是让，是建议
【RBQ要造反】h_ang!(J2, 7);<huangjj.27@qq.com> 10:12:17教唆国家人才变更国籍 不得了不得了 //
【u8】東491(735151965) 10:12:32@h_ang!(J2, 7); 对啊
【u8】東491(735151965) 10:12:37所以不能说太多
【u32】你妹啊007(781261736) 10:12:37听起来好牛逼。。。
【u8】東491(735151965) 10:12:42
【先怀个孕为敬】野了个喵了个咪<crlf0710@gmail.com> 10:13:03RangeInclusive 没有实现Copy……
【先怀个孕为敬】野了个喵了个咪<crlf0710@gmail.com> 10:13:10真坑
【RBQ要造反】h_ang!(J2, 7);<huangjj.27@qq.com> 10:13:14算了 我已经听不懂你们在聊什么了……
【u32】你妹啊007(781261736) 10:13:30那你以后不要给我们讲这些了
【RBQ要造反】h_ang!(J2, 7);<huangjj.27@qq.com> 10:13:31@野了个喵了个咪 e mm 你想怎么用？
【u32】你妹啊007(781261736) 10:13:44万一泄密了大家都不好
【u32】你妹啊007(781261736) 10:13:47
【RBQ要造反】h_ang!(J2, 7);<huangjj.27@qq.com> 10:13:53
【先怀个孕为敬】野了个喵了个咪<crlf0710@gmail.com> 10:14:12copy啊……
【u8】東491(735151965) 10:14:15对对对，理解万岁
【先怀个孕为敬】野了个喵了个咪<crlf0710@gmail.com> 10:14:22let a = range;let b = range;
【u32】你妹啊007(781261736) 10:15:38李姐万岁
【RBQ要造反】h_ang!(J2, 7);<huangjj.27@qq.com> 10:15:48仔细一想 好像正交光源可以实现 相反电源输出电压的效果
【先怀个孕为敬】野了个喵了个咪<crlf0710@gmail.com> 10:15:53乌拉~
【u128】智商药水(737445366) 10:16:10
【RBQ要造反】h_ang!(J2, 7);<huangjj.27@qq.com> 10:16:18如果是光电路的情形下
【RBQ要造反】h_ang!(J2, 7);<huangjj.27@qq.com> 10:16:35// 诶 我是不是不小心泄密了
【u8】東491(735151965) 10:16:43@h_ang!(J2, 7); 噗
【u8】東491(735151965) 10:16:49在泄密的边缘试探
【RBQ要造反】h_ang!(J2, 7);<huangjj.27@qq.com> 10:17:03 我瞎猜的， 没有毫无科学根据

**Comment by absente** [comment]
【RBQ要造反】h_ang!(J2, 7);<huangjj.27@qq.com> 10:18:53脑洞大开： 上面我说的光路 自带二进制传输兼容 刻印参入2进制码。实现e进制 达到最高信息密度 哈哈哈哈
【u8】東491(735151965) 10:19:04@h_ang!(J2, 7); 对，自带兼容
【u8】東491(735151965) 10:19:38至于可不可以实现e进制，还有待验证，讲道理可以试试看，以及pi进制，0.618等等等
【u8】東491(735151965) 10:21:00https://github.com/secti6n/v2/releases/tag/12.15
【RBQ要造反】h_ang!(J2, 7);<huangjj.27@qq.com> 10:21:15只是缺乏限制了我的想象力
【RBQ要造反】h_ang!(J2, 7);<huangjj.27@qq.com> 10:21:43@野了个喵了个咪 emmm 这么做的目的是什么？
【优化鬼才】咸鱼六号.cc(291020359) 10:22:54你们还没有屏蔽这个人吗
【u8】東491(735151965) 10:23:02噗
【u8】東491(735151965) 10:23:04暴露了
【先怀个孕为敬】野了个喵了个咪<crlf0710@gmail.com> 10:23:28@h_ang!(J2, 7); 我逻辑要用啊
【u8】東491(735151965) 10:23:39@野了个喵了个咪 有点意思
【大鸟】pengpengche(2457417431) 10:23:44三进制没问题吧指令是二进制就通用
【u32】你妹啊007(781261736) 10:23:50爪机屏蔽不了啊
【优化鬼才】咸鱼六号.cc(291020359) 10:24:07能啊
【u8】東491(735151965) 10:24:10@pengpengche 对啊，所以我不知道嘲讽我的人，是谁给的勇气和正义感
【优化鬼才】咸鱼六号.cc(291020359) 10:24:12点头像
【优化鬼才】咸鱼六号.cc(291020359) 10:24:16就有了啊
【优化鬼才】咸鱼六号.cc(291020359) 10:24:38
【肉便茶壶弟弟】开始学Rust(295947730) 10:24:54这个群连Rust都能讨论，怎么3进制不让人讨论
【u8】東491(735151965) 10:25:50@开始学Rust 9494
【大鸟】pengpengche(2457417431) 10:26:08比如可以实现一个只接受01不接受3的加法指令
【D语言已死】MoGu<mogud@qq.com> 10:26:18三进制吼
【大鸟】pengpengche(2457417431) 10:26:22是2写错
【u8】東491(735151965) 10:26:24@pengpengche 我们其实用的是0,1,-1,
【i64】CountStarlight(785808803) 10:26:263进制相比2进制有什么优势吗
【u8】東491(735151965) 10:26:37参考了前苏联的方案
【u8】東491(735151965) 10:26:44@CountStarlight 自带三值逻辑
【D语言已死】MoGu<mogud@qq.com> 10:27:00信息密度高很多
【u8】東491(735151965) 10:27:05true, unknown/undefined，false
【i64】CountStarlight(785808803) 10:27:33感觉计算机的瓶颈不在这里
【大鸟】pengpengche(2457417431) 10:27:35这样可以高效处理sql毕竟sql只有三值逻辑
【u8】東491(735151965) 10:27:43@pengpengche 对
【u8】東491(735151965) 10:27:46一语中的
【D语言已死】MoGu<mogud@qq.com> 10:27:54编程三态逻辑也很方便
【先怀个孕为敬】野了个喵了个咪<crlf0710@gmail.com> 10:28:14诶，蘑菇聚聚
【RBQ要造反】h_ang!(J2, 7);<huangjj.27@qq.com> 10:28:18@pengpengche 什么意思？
【先怀个孕为敬】野了个喵了个咪<crlf0710@gmail.com> 10:28:27不如D~
【u8】東491(735151965) 10:28:30@CountStarlight 瓶颈是冯诺依曼架构，所以Google有TPU，是非冯的
【优化鬼才】咸鱼六号.cc(291020359) 10:28:55硅基都到头了
【优化鬼才】咸鱼六号.cc(291020359) 10:29:04只能堆料了
【大鸟】pengpengche(2457417431) 10:29:06不不不计算机的瓶颈在于造硬件有成本
【优化鬼才】咸鱼六号.cc(291020359) 10:29:11还研究啥
【优化鬼才】咸鱼六号.cc(291020359) 10:29:38就算弄出了三进制也不能有数量级的提升
【大鸟】pengpengche(2457417431) 10:29:52可以有
【i16】天明(760298325) 10:29:59非冯不是对冯氏的颠覆，而是对冯氏的补充
【先怀个孕为敬】野了个喵了个咪<crlf0710@gmail.com> 10:30:12@東491 我对你说的那些都不感兴趣，所以我决定暂时无视你【
【u32】imoyaki-菜鸡用rust写bug(2509556310) 10:30:14
【大鸟】pengpengche(2457417431) 10:30:15比如专门做三进制计算
【u32】imoyaki-菜鸡用rust写bug(2509556310) 10:30:32不是缺乏能表示01之外的芯片吗
【管理员】JonirRings-切图仔-成都<i@jonirrings.com> 10:30:35哈佛架构和普林斯顿架构？
【语录达人】Solmyr(12367308) 10:30:38我觉得吧，虽然军用比民用不差钱，但还是不能费太多，类比算法复杂度的话，类似于都是在同一个复杂度下，只不过军用的系数可以大一点
【u8】東491(735151965) 10:30:39@野了个喵了个咪 ok，dont matter
【大鸟】pengpengche(2457417431) 10:30:43问题就是啥地方必须三进制
【u32】imoyaki-菜鸡用rust写bug(2509556310) 10:30:52后来有了记忆电阻
【u8】東491(735151965) 10:30:54@天明 同意
【优化鬼才】咸鱼六号.cc(291020359) 10:30:56研究一下量子和光子计算机才是重点
【管理员】JonirRings-切图仔-成都<i@jonirrings.com> 10:31:10
【优化鬼才】咸鱼六号.cc(291020359) 10:31:18算力够了模拟一下三进制不好吗
【u8】東491(735151965) 10:31:19@Solmyr 这个军方也知道的
【优化鬼才】咸鱼六号.cc(291020359) 10:31:26为什么要原生

**Comment by absente** [comment]
【u8】東491(735151965) 10:31:39@咸鱼六号.cc 所以这就是光子的分支，光通信嘛
【大鸟】pengpengche(2457417431) 10:31:46量子也是特定算法才需要本质上差不多
【优化鬼才】咸鱼六号.cc(291020359) 10:32:14我又被老师骗了吗
【优化鬼才】咸鱼六号.cc(291020359) 10:32:29我们学校有一个搞量子计算的
【优化鬼才】咸鱼六号.cc(291020359) 10:32:39讨论过一丢丢
【大鸟】pengpengche(2457417431) 10:32:59造硬件如果成本比写软件还低这些瓶颈都可以解决
【u8】東491(735151965) 10:33:22@pengpengche 正解
【u8】東491(735151965) 10:33:37@咸鱼六号.cc 量子是base4，光是base3
【u32】imoyaki-菜鸡用rust写bug(2509556310) 10:33:47
【u32】imoyaki-菜鸡用rust写bug(2509556310) 10:34:02有大佬提示一下吗，函数指针怎么声明生命周期
【优化鬼才】咸鱼六号.cc(291020359) 10:34:09
【u8】東491(735151965) 10:34:10@咸鱼六号.cc 对，就是因为模拟量子态，成本高，所以没我们才base3
【u32】殒命大厦(825707653) 10:35:52
【u8】東491(735151965) 10:36:32erlang大法好？
【大鸟】pengpengche(2457417431) 10:36:55https://crates.io/crates/gmagickhttps://crates.io/crates/magick_rust看见2个
【u32】imoyaki-菜鸡用rust写bug(2509556310) 10:36:55没人出来讨论rust了吗

**Comment by absente** [comment]
是: 三进制有个很严重的问题

是: 除了功耗墙 还有磁感墙

Dj刘#: 请教？

Dj刘#: 光通路可以回避

Dj刘#: 我现在的策略是，HAL模拟光通路

是: 这个群禁止讨论 https://github.com/program-in-chinese/ 的所有东西

Dj刘#: 好的

是: 看了一下

Dj刘#: 明白了

是: 这个git的人

是: 读书太少

是: 想的太多

Dj刘#: 嗯

Dj刘#: 所以叫git hub，不矛盾

是: 我初一学高等物理 奥赛金牌 

是: 一看这他妈就看不下去了

Dj刘#: 噗

是: 全是民科

Dj刘#: 全员民科还行

Dj刘#: 66

是: 还黄绿光呢 当是信号灯么

是: 说这话的人 完全不懂光学

Dj刘#: 嗯，有可能

是: scheme 中文化 一个人一小时可以做完 还讨论什么…

是: 知道intel一年的研发费用么 这么多钱 能想不到民科想到的东西？不要一天想搞个大新闻

是: 有空看看 普通语言学教程

是: 看看 高等物理

Dj刘#: 嗯，好的

是: 别人是看书太多 没思考

是: 这些人是思考太多 没看书

Dj刘#: 同意

是: 你看看光学部分

是: 知道我说的啥了

是: 其实我搞语言学之前是搞量子力学的

Dj刘#: 牛逼了啊

Dj刘#: 服

是: @NTFS#深圳.erl,sicp35% 我昨天实现scheme调用python库了你服不服

是: [图片]

Dj刘#: 不服不行呐，效率惊人

Dj刘#: 我估计我做erlang/chez的互通，怎么也要个一个月

是: 你没找到关键点

是: 关键点是 所有语言的ffi接口

是: 都是用了c的abi

Dj刘#: 这个我知道的

Dj刘#: 但是自己abi这块，确实水平不行

Dj刘#: 所以我参考的不是julia，而是haxe（主要

Sebastian Lin: c是真正的胶水语言

Dj刘#: 所以，py是真正的cpp？

是: c是真正的胶水语言 +1

-------------

关于，c是abi的本质，这点，我认为，光可以作为通用的信号传输介质，这两点，应当是相同的。（注意，这句话符合三值逻辑

**Comment by nobodxbodon** [comment]
没有看出此话题与中文编程的关系.
另外, 请尽量避免拷贝整段聊天记录. 总结后的文档可读性会好很多.

**Comment by absente** [comment]
@nobodxbodon 我的REPL，最终要用三进制改造底层。所以还是有关的，但是close是因为，和中文编程关系不大。关于避免的问题，我会注意的，现在已经在整理了。
