### ISSUE TITLE
讨论组的主页, 对外名称, 徽标?

### ISSUE THREAD

**Issue by nobodxbodon** [program-in-chinese/overview#12]
随着新项目的开展, 迟早需要作为一个团队对项目进行维护和推广. 是否最好有个主页, 至少发布一些项目进度/发布的消息? Github page是否适合?

另外, github的默认图标虽然不是太难看, 但肯定不算美观. 也请推荐一下.

**Comment by nobodxbodon** [comment]
因为暂且没有主页, 每周简报暂时这里和[知乎](https://www.zhihu.com/question/62953512)(对外)更新, 比如最近两周:

> 好像没有发现在所有编程语言中实践用中文编程的讨论组. 一周推广下来, github的讨论组已有10位新成员. osc上暂时没有发现活跃成员, 接下来的讨论重心会在github.
现有的成员中有各种领域和背景的开发者, 使用的语言包括.Net, Python, Kotlin, OCaml, Java, JavaScript等等. 发现了用中文编写Python3代码实现自然语言处理工具的实用项目, 代码量和成熟程度很可观. 

> --- 20170807 ---
新增10位新成员. 其中包括用插件在vscode自动补全中实现拼音输入匹配中文的作者. 
进行了热烈友好的技术讨论, 增进互相了解.
开展一些实验项目, 包括中文DSL, 汉化JUnit 等等. 
将之前在个人账号下的相关代码库fork到讨论组下`

欢迎补充.

**Comment by nobodxbodon** [comment]
已开github pages: https://program-in-chinese.github.io/overview/ 暂时作为讨论组主页, 将添加周报等内容.

**Comment by nobodxbodon** [comment]
暂以"文"字为徽标, 取"以文会友"之意.

**Comment by nobodxbodon** [comment]
@program-in-chinese/all 本周开始周报在[github主页](https://program-in-chinese.github.io/overview/)更新. 难免遗漏内容, 欢迎各位补充.

**Comment by nobodxbodon** [comment]
在JUnit4[项目讨论]((https://github.com/program-in-chinese/junit4_in_chinese/pull/2#discussion_r132850374))中, 发现只要开发者各自签名即可, 因此暂时不用确定团队名称.

**Comment by drduan** [comment]
表示呲呲

**Comment by nobodxbodon** [comment]
@drduan 有何高见?

**Comment by nobodxbodon** [comment]
讨论组开展近三个月, 收获颇丰.
基于overview代码库的流量分析, 绝大多数仍是来自github自身.
![screen shot 2017-10-22 at 2 57 45 pm](https://user-images.githubusercontent.com/392497/31866790-9ba73b48-b739-11e7-9ddb-7648b78749de.png)
考虑注册域名, 仍然以开源形式维护一个先期以静态内容为主的网站, 作为讨论组对外窗口. 欢迎对网站设计/维护/SEO有经验的组员出谋划策, 包括域名是否在国内注册等. 
先试试把[现在的github page](https://program-in-chinese.github.io/overview/)绑定到我的一个测试域名看.

**Comment by nobodxbodon** [comment]
github page绑定没有问题.
已创建[网站代码库](https://github.com/program-in-chinese/team_website). 由[讨论组管理员](https://github.com/program-in-chinese/overview/issues/38)进行代码提交, PR审核/合并等.

**Comment by nobodxbodon** [comment]
初步的网站内容规划. 请多提意见.
- 综合: 中文编程的历史, 现状, 展望
- 讨论组博客/周报, 项目简介
- 论坛(?):
  - 在代码中使用中文命名出现的问题
  - 新创中文编程语言的发布和答疑

**Comment by nobodxbodon** [comment]
初步决定论坛功能仍然依托github讨论组. 因为个人不可能兼顾另一个论坛管理. 
网站内容短期内以静态内容为主, 提供链接到github内容.
希望有对github page有经验的参与开发网站.

**Comment by nobodxbodon** [comment]
已经绑定到 [codeinchinese](http://codeinchinese.com/). 暂时仍用博客样式. 发布了第一贴.

**Comment by nobodxbodon** [comment]
@program-in-chinese/all  已在[codeinchinese网站](http://codeinchinese.com/)发布了几篇之前的文章，请各位多提建议意见。欢迎在[网站源码库](https://github.com/program-in-chinese/team_website)参与添加维护内容，探讨相关问题。

**Comment by nobodxbodon** [comment]
还是加了disqus
国内访问速度比较慢:
![screen shot 2017-11-04 at 2 23 48 pm](https://user-images.githubusercontent.com/392497/32409598-167227f2-c16c-11e7-8795-539d432315ce.png)
不知有什么办法改进. 镜像? CDN?

**Comment by absente** [comment]
如果需要设计徽标，表示可以帮忙

**Comment by absente** [comment]
![4425831377168588](https://user-images.githubusercontent.com/1655223/42880593-67d88512-8ac7-11e8-8a30-58b3b7741873.jpg)
@nobodxbodon 这个红中如何？

**Comment by nobodxbodon** [comment]
个人希望是徽标能显示"中文"和"编程"两个含义, 因为在非程序员圈子中, 单个的'中'或者'文'字都不大能和编程联系起来. 当初取'文'也主要是因为活动在github为主的缘故, 所以没有特别加"编程"的含义.

另外, 这个有点容易联想到这个吧...
![screen shot 2018-07-18 at 4 10 02 pm](https://user-images.githubusercontent.com/392497/42912662-5fb366e4-8aa5-11e8-9264-fcb578ac5723.png)

**Comment by absente** [comment]
![image](https://user-images.githubusercontent.com/1655223/43378306-a1205eaa-93f8-11e8-8696-be10781c2e19.png)
@nobodxbodon 我把饭否头像改成这个了

**Comment by nobodxbodon** [comment]
在形成核心项目群(全组或者多数人愿意以各种形式投入贡献的一组内容相关的项目)之前, 考虑暂时还是围绕具体项目, 由各个项目的团队进行分别宣传.
