### ISSUE TITLE
参与中文编程的动因?中文编程是什么?以及自然语言编程的未来会是怎样?

### ISSUE THREAD

**Issue by gchihiha** [program-in-chinese/overview#138]

**Comment by gchihiha** [comment]
谈具体如何实现

目前现状：
编程语言，更贴近数学和机器一些，而且结构化编程是解决过程性问题的最佳方式，没有之一。
自然语言，尤其是口语，歧义很多，用法复杂。

我认为正确的实现姿势：
对于过程性问题，应当运用结构化编程。
对于更高层次的问题，可以使用自然语言去描述。
对于自然语言，需要提炼，去除歧义，以及不够清晰的地方，提炼出核心的部分。

**Comment by RimoChan** [comment]
我有「這個issue下面會演變成宗教戰爭」的預感了……

說中文編程之前先說一說「英文編程」，英文編程的直接原因必然是書上的代碼是英文、或者網上教程的代碼是英文、或者學校老師的代碼是英文。但歸根結底是前幾個世紀美國殖民者的文化傳播。誰都知道機器只認0|1，爲什麼偏要打英語字母，恐怕文化的影響很大。
說起來，如果當時用堅船利炮佔領美洲的是中國人，現在char就是16位了，而且可能要改名叫「字」。

我非常希望「一切都是中文的」，希望我們的國家有一天也能站在世界民族的巔峰，能將文化傳播到地球的各個角落，世界人民自發地學習使用中文，用中文寫論文，用中文編程。
且我更希望「現在的所有的中國人都這樣希望」，這樣的期望是任何一個中國人都不可或缺的。
(當然我這樣說不是針對斷水流，沒有任何指責的意思。如果你不喜歡的話就把我當成〇〇主義吧。)

不過話說回來，英文難嗎，當然難。在壞的意義上，工具發明出來就是給人使用的，當然要讓儘可能多用戶的用戶以最小的學習成本來用，用戶覺得難，肯定語言是有問題的。別人說c語言難的時候我也不會去嘲笑他。畢竟是上個世紀的設計，其中壞處的確不少，相比之下說python難的就比較少。
語言先有詞法，再有語法，再有語義。英文卻反過來，用語義決定詞法，這是純粹地添加學習者的負擔，就是一種壞的表現了——當然比不上「公貓是陰性的」來的壞。
當然中文壞處也不少，比如公認的——看起來像泡麪(笑)。對於字形繁雜的問題，建國以來這個壞處也優化過一段時間，不過現在的美國人肯定是不願意優化他們該死的層次耦合問題了。

<hr>

關於自然語言編程，
我有點在意的是——
> 自然语言编程 …… 绝不是使用类似谷歌翻译背后NLP的AI技术。

爲什麼不用NLP的AI技術？我自己試用的時候感覺還挺順利的([【幻書】能編程的自然中文！](https://github.com/RimoChan/Gensho))，只要假以時日這個技術完全可以用來編程。

**Comment by nobodxbodon** [comment]
建议分开讨论: 
对"中文编程"含义的探讨请移步 [专用帖: 对中文编程的质疑, 困惑, 批评, 吐槽请到此处](https://github.com/program-in-chinese/overview/issues/44)
对自然语言与中文编程的结合的**具体技术相关**讨论, 建议开新帖.
