### ISSUE TITLE
Edit privilige

### ISSUE THREAD

**Issue by ice1000** [program-in-chinese/overview#14]
I can't edit anything except by starting a pull request. Could you please give me write access?

**Comment by nobodxbodon** [comment]
所有人都在 @program-in-chinese/all team里, 应该有所有讨论区的read/write权限(刚加了遗漏的.Net区权限). 你不能提交的是哪个repo?

**Comment by ice1000** [comment]
就这个仓库啊

**Comment by nobodxbodon** [comment]
![screen shot 2017-08-02 at 10 12 03 am](https://user-images.githubusercontent.com/392497/28885547-232480ee-776b-11e7-8b00-07068f53edc0.png)

**Comment by ice1000** [comment]
试了下，可以了。
