### ISSUE TITLE
IDLE中文输入问题

### ISSUE THREAD

**Issue by nobodxbodon** [program-in-chinese/overview#156]
源自qq群 @laowu2019 
> 把微软或搜狗拼音输入法调成“中文输入、英文标点”模式，然后尝试在Python IDLE里输入键盘第二排数字上方的字符，就是按shift键加数字，看能不能正常输出括号、感叹号等字符

请详述环境(版本等), 以便他人验证.

个人测试过下面两个环境:
- Mac, IDLE 3.6.5, 搜狗拼音输入“中文输入、英文标点”模式. 输入正常: [视频](https://zhuanlan.zhihu.com/p/38324987)
- Windows 7 pro 64位, IDLE 3.6.5, 搜狗拼音输入“中文输入、英文标点”模式. 输入正常

**Comment by laowu2019** [comment]
我的环境是 Windows 10 专业版，版本号1809。两台电脑都是这样。

**Comment by nobodxbodon** [comment]
@laowu2019 [这里](https://www.v2ex.com/t/564262#r_7327287)反馈win10没问题. 请问你的python版本是?

**Comment by nobodxbodon** [comment]
@laowu2019 [后面](https://www.v2ex.com/t/564262#r_7328018)反馈 3.7.3 有问题.

刚在mac下测了3.7.3, 好像没问题:
![20190514_IDLE输入](https://user-images.githubusercontent.com/392497/57753258-86355d80-76a0-11e9-8eae-bea6d3109b54.gif)

**Comment by laowu2019** [comment]
那么这个问题复杂了，祸首是哪一个，IDLE、win 10还是输入法本身？

**Comment by nobodxbodon** [comment]
@laowu2019 请问这个问题解决了吗？原因在哪里？

**Comment by laowu2019** [comment]
没有解决. 原因尚未知.

**Comment by nobodxbodon** [comment]
暂无进展或深究打算。
