### ISSUE TITLE
打算在20天之内用业余时间做一个小项目或者阶段成果, 有建议吗?

### ISSUE THREAD

**Issue by nobodxbodon** [program-in-chinese/overview#16]
下面是自认为可以一试的方向(排在越前面的越不可控):

- 用中文代码做一个Java库, 实现可以扩展的类自然语言中文编程原型(语言功能会最小化, 最主要目的是概念验证)
- 用中文Java代码重头做早先刚开头的[实践"两周自制脚本语言"一书](http://tieba.baidu.com/p/4563689271)
- 完成[JavaScript编程一天入门](https://github.com/program-in-chinese/javascript-in-a-day-chn)初稿

**Comment by nobodxbodon** [comment]
基本决定前两个之一. 将在Java区新开issue进行进一步计划.

**Comment by sih4sing5hong5** [comment]
https://github.com/program-in-chinese/overview/issues/9#issuecomment-319624450

**Comment by nobodxbodon** [comment]
多谢提醒, 刚回复了. 非常赞同你的1-4的排序. 确实第一个是非常不实际的一个目标, 之前我也提到创建新语言是一个远期而不是短期目标. 主要是因为我这20天之后的业余时间会减少很多, 所以想用相对整块的时间尝试一些比较"疯"的想法, 而且仅限于这20天. 在那之后应该会更脚踏实地从API做起 :)
这个语言原型是非常幼稚的, 只是想把一点之前的想法具现化出来. 即使不能完全演示出来, 也至少写出可供讨论的文档.
