### ISSUE TITLE
另一种中文编程的实现方式

### ISSUE THREAD

**Issue by cycpe950609** [program-in-chinese/overview#170]
（手机排版，请见谅）
我有一个计画，关于图形化编程语言，虽然并不是中文编程，但目标是能用「母语」编程，概念来自[Jetbrain MPS](https://www.jetbrains.com/mps/) 的AST树。
* 我们需要一个通用的AST，如[Babelfish](https://github.com/bblfsh/bblfshd) 的UAST，或者一种自制的语言，基本语素是名词、动词、介系词，文法就是SVO等（还是多少受英文影响😅）。
* 一个通用的转译方式，转成中文的AST树
* 将AST树的内容显示在萤幕上(跟MPS一样），也就是说前端也可以是英文/日文等

**Comment by cycpe950609** [comment]
我看到多数「中文编程」是将英文翻成中文，希望能减轻初学者或英文能力较差的人的负担，我的想法是从图形化编程下手，的确中文（应该是说母语）可以减轻理解的难度，但图示是世界各国通用的，如果能用符号代表所有逻辑（类似LabView），当然很好。但如果图形化编程像Scratch，我们就需要母语的帮助

**Comment by nobodxbodon** [comment]
已有[编程猫](https://zhuanlan.zhihu.com/p/33650956)

**Comment by cycpe950609** [comment]
> 已有编程猫


原来有这么完整的类Scratch IDE😁，不过我的目标是专业（大概就像C++那种），有特殊输入法的编辑环境，而且可以不同人看不一样的语言，但是是同一份程式码:D
