### ISSUE TITLE
试以单字译C#

### ISSUE THREAD

**Issue by liuxilu** [program-in-chinese/overview#181]
volatile  谲(诡谲)/㪐(不稳)/愅(改变)/憙(有叶者～烂)/憣(迅速改变：为谁书到便～然)/嫳(易怒)/儇(轻浮)/卮(卮言)/愆(愆伏)/罔(罔极)(词义可疑)（过多，下表只取一）
object  旨/㫑　while  期
async  逐　sync  骈
switch  检　case  索
if  若　else  另
for  以　foreach  每　in  在

|||
|-|-|
命名空间|using  用　namespace  名　alias  号　global  总
访问域|private  私　internal  内　protected  护　public  公
|||
类|class  类　interface  接　struct  构　enum  举
限制|abstract  象　static  静/侀/佁　sealed  封　virtual  虚　partial  部
操作|default  缺　sizeof  寸　typeof  型
继承|override  覆　new  新　this  此　base  基
|||
算子|explicit  显　implicit  隐　operator  操
限制|delegate  委　event  事　extern  外
-|add  添　remove  除　get  取　set  设/置　value  值
参数|in  进　out  出　ref  引　params  多
并行|async  逐(𪠆)/䢔遝(行相及)𭮎(⿰歹并 新解歹表否定)　sync  骈　await  候/待/等
|||
试错|try  试　catch  捉　when  当　finally  终
循环|do  做　while  期/当/限　for  以　foreach  每　in  在　break  断　continue  续
流程|if  若　else  另　switch  检　case  索　when  当　goto  去　return  返　yield  迭　throw  丢
块标记|using  用　unsafe  危　lock  锁　checked  查/察/溢　unchecked  不查/盈(溢不出)/荃(荃不察)
|||
定义|void  空　var  变　dynamic  动　bool  俩　object  旨/㫑　char  字　string  串
_|byte  节　short  短　int  整　long  长　float  浮　single  单　double  双　decimal  十
_|sbyte  正负节　ushort  正短　uint  正整　ulong  正长
限制|volatile  谲　const  定　readonly  只读　fixed  固　stackalloc  栈配
操作|as  为　is  是　null  无　true  真　false  假
|||
LINQ|let  让　where  哪？　select  选
_|from  自　join  连　in  在　on  当　equals  同　group  组　by  以　into  入
_|orderby  序　ascending  正　descending  倒
|||
泛型|where  哪？　in  缩？　out  扩？

(#40) [参](https://www.etymonline.com)[考](https://www.mdbg.net/chinese/dictionary?page=chardict&cdqdef)[资](http://yedict.com/zsFan.asp)[料](https://zdic.net)

杂记
;|volatile: "evaporating rapidly" (c. 1600), from Middle French volatile, from Latin volatilis "fleeting, transitory; swift, rapid; flying, winged," （飞->挥发！） from past participle stem of volare "to fly" (see volant). Sense of "readily changing, flighty, fickle" is first recorded 1640s.
;|审/核/校/验/检/查/察/甄/考/究/𬤞(𧬇)/瞩
;|表/列/排/沓/叠//目/录/阵(𨸬)/队/典/例/编/集/辑/谱/卷/汇;栈/堆/複/陈/映/射

**Comment by nobodxbodon** [comment]
如有后续补充请到 [wiki](https://github.com/program-in-chinese/overview/wiki/%E8%8B%B1%E6%96%87%E5%85%B3%E9%94%AE%E8%AF%8D%E6%B1%89%E5%8C%96)
