### ISSUE TITLE
{

### ISSUE THREAD

**Issue by foreverlove2361** [program-in-chinese/overview#189]
{
  "timestamp": 1618678640100,
  "message": "success",
  "data": {
    "statistic": [
      1,
      0,
      0
    ],
    "reviewCount": 0,
    "fileList": [
      {
        "label": 0,
        "tag": "W/\"1ef-wLG7L0BpFmsK9buCouPwzesWp60\"",
        "rate": 0.95527924308022,
        "name": "42924E6D-FBA9-41EC-BEA5-4202BCE48BB5.jpeg",
        "review": false
      }
    ]
  },
  "code": 0,
  "nonce": "0.4859186912274658"
}

__Originally posted by @foreverlove2361 in https://github.com/program-in-chinese/overview/issues/188__

**Comment by nobodxbodon** [comment]
什么情况？
