### ISSUE TITLE
请大家帮忙投票：关于vscode官方支持中文传统竖排显示模式的功能

### ISSUE THREAD

**Issue by UltimatePea** [program-in-chinese/overview#195]
在向vscode官方团队建议加入支持中文传统竖排显示模式的功能，如果大家感兴趣的话，请帮忙个投票（点击问题下方大拇指（👍）图标），谢谢！链接：https://github.com/microsoft/vscode/issues/152005

**Comment by UltimatePea** [comment]
<img width="654" alt="截屏2022-06-30 下午3 29 39" src="https://user-images.githubusercontent.com/9295852/176781672-825a0857-0417-494a-9d28-1a7fce050f4f.png">

**Comment by nobodxbodon** [comment]
已转发gitee：https://gitee.com/Program-in-Chinese/overview/issues/I5EZX7

话说这种功能估计日本开发者更会有需求，不知有没有类似插件？印象里某个日语编程语言就支持竖排开发。

**Comment by nobodxbodon** [comment]
已24票，足够了？
<img width="507" alt="Screen Shot 2022-07-04 at 1 45 11 PM" src="https://user-images.githubusercontent.com/392497/177214893-bed9aca3-2de4-4f2c-be2f-fcafa4f88682.png">

**Comment by UltimatePea** [comment]
> 已24票，足够了？
> <img alt="Screen Shot 2022-07-04 at 1 45 11 PM" width="507" src="https://user-images.githubusercontent.com/392497/177214893-bed9aca3-2de4-4f2c-be2f-fcafa4f88682.png">

应该是够了，在等vscode官方bot accept

**Comment by UltimatePea** [comment]
官方已经接受，谢谢大家！

**Comment by FlashMan2008** [comment]
请问如何使用竖排功能？

**Comment by UltimatePea** [comment]
要等vscode官方将这个提案纳入开发日程，（预计时间可能在两年到三年以上）， 才可以在vscode里面使用这个功能。

**Comment by nobodxbodon** [comment]
@FlashMan2008 [这个插件](https://marketplace.visualstudio.com/items?itemName=n-fukuju.vertical-writing) 有竖排预览功能：
<img width="945" alt="Screen Shot 2022-09-07 at 5 40 54 PM" src="https://user-images.githubusercontent.com/392497/189008777-a59dc5d1-54b5-491d-bf47-9fe9bac08bde.png">

**Comment by xgongya** [comment]
您好，您的邮件已收到，会尽快处理回复您！

**Comment by nobodxbodon** [comment]
未见进展，也许求人不如求己。
