### ISSUE TITLE
TDM-GCC64 don't Support Chinese?

### ISSUE THREAD

**Issue by FlashMan2008** [program-in-chinese/overview#196]
你好，我正在用TDM-GCC64最新版本编译我的C++文件。它是不支持中文吗？如果是，那些C++编译器支持中文呢？
谢谢

**Comment by nobodxbodon** [comment]
记得gcc10开始应该支持unicode标识符了。可否贴一下具体版本号和报错信息？

**Comment by nobodxbodon** [comment]
[之前](https://github.com/program-in-chinese/overview/blob/master/%E7%A4%BA%E4%BE%8B%E4%BB%A3%E7%A0%81/%E9%97%AE%E5%A5%BD.cpp) 测的 g++，印象里 VS、IntelliJ 系列也支持。

**Comment by xgongya** [comment]
您好，您的邮件已收到，会尽快处理回复您！
