### ISSUE TITLE
为什么没有设置C/C++的讨论区？

### ISSUE THREAD

**Issue by swizl** [program-in-chinese/overview#21]
java js py都有讨论区，为什么c/c++没有

**Comment by nobodxbodon** [comment]
非常欢迎创建新讨论区并发表内容。

**Comment by nobodxbodon** [comment]
@swizl 如果方便的话请参照现有讨论区创建一个新区. 因为本人对c/c++不熟, 所以希望有专攻的组员志愿维护. 创建后就可以关闭此issue.

**Comment by swizl** [comment]
创建了
