### ISSUE TITLE
将Prolog中文化

### ISSUE THREAD

**Issue by nlpguyz** [program-in-chinese/overview#24]
- 测试主流Prolog实现是否支持中文utf-8, 以及unicode smp
- (如支持) 建立中文prolog例程库
- (如不支持) 修改prolog解释器源码, 使其支持中文程序

**Comment by nobodxbodon** [comment]
赞! 请问有没有什么特别原因从Prolog入手呢? 是否有什么项目想用Prolog实现?
swi-prolog似乎对unicode代码有[一些支持](http://www.swi-prolog.org/pldoc/man?section=unicodesyntax)

**Comment by nlpguyz** [comment]
多谢！主要原因是Prolog擅长于简单的自然语言处理和逻辑编程。我先测试一下swi-prolog吧。

**Comment by nobodxbodon** [comment]
它在逻辑编程的地位略有了解. 刚搜了一下它在nlp方面的应用好像资料不是很多. 
很高兴看到对不同类型编程语言的兴趣. 尤其它的语法也蛮接近自然语言. 感觉对创建新语言应该也蛮有借鉴意义.

**Comment by nobodxbodon** [comment]
请问有什么发现?

**Comment by nlpguyz** [comment]
SWI-prolog支持MBCS，测试了一些中文标识符，运算没有问题。但是界面显示有问题，光标会出现错位。还是需要修改。

**Comment by nobodxbodon** [comment]
多谢! 能否麻烦你分享一下你的测试代码, 然后在overview的[语言列表](https://github.com/program-in-chinese/overview#%E5%85%B3%E9%94%AE%E8%AF%8D%E4%B8%BA%E8%8B%B1%E6%96%87%E7%9A%84%E7%BC%96%E7%A8%8B%E8%AF%AD%E8%A8%80%E5%AF%B9%E4%B8%AD%E6%96%87%E4%BB%A3%E7%A0%81%E7%9A%84%E6%94%AF%E6%8C%81%E5%AD%97%E6%AF%8D%E6%8E%92%E5%BA%8F)加个链接?

**Comment by nobodxbodon** [comment]
@nlpguyz 请问能把测试代码和运行方法贴一下吗? 我可以代为提交. 个人也对prolog有兴趣.

**Comment by nobodxbodon** [comment]
@nlpguyz 期待回归后issue重开!
