### ISSUE TITLE
为量子计算设计的中文编程语言

### ISSUE THREAD

**Issue by nobodxbodon** [program-in-chinese/overview#29]
@Roger-Luo 有幸看到你的[知乎回答](https://www.zhihu.com/question/44784094/answer/102271295)
另外 @i2000s 刚拜读大作[对近期一些量子计算进展的评论](https://www.qixiaodong.tk/cn/2017/05/07/comment-on-recent-quantum-computing-progress.html)
想请教两位, 设计一种中文编程语言进行量子编程, 是否有意义? 有些什么前提条件需要满足, 比如类似[Quantum Playground](http://www.quantumplayground.net/)的量子计算模拟环境? 
在下对量子计算只有零星了解, 还请多多指教.

**Comment by i2000s** [comment]
可以尝试在相关模拟环境下搭建。建议接口尽可能通用，以便未来核心部分成熟后迁移。暂未有具体建议。

赞

**Comment by absente** [comment]
我觉得有意义，不过还是取决于设计和实现的形式。

**Comment by nobodxbodon** [comment]
暂时搁置. 期待对量子领域有专攻的同仁重开此帖.
