### ISSUE TITLE
如果用已有的中文编程语言来设计编译器呢.如何?

### ISSUE THREAD

**Issue by qwas982** [program-in-chinese/overview#34]
我现在又萌发了新思路,在已有汉语编程语言的基础上,创造一门新的汉语编程语言,然后用 -汉语编程语言的编译器,编译 新的汉语编程语言, 得到一个编译器 ,然后用这个编译器再编译一遍-新的汉语编程语言 ,得到第二个编译器,然后再用第二个编译器再编译一遍, 新的汉语编程语言, 于是得到第三个编译器,这个编译器就是完全的汉语编程语言.
这里, 我决定用易语言来写编译器a,  也就是-第一个编译器, 得到第一个编译器的可执行程序后就可以用创造的语言来写编译器b, 然后用前面的可执行程序编译, 编译 编译器b .

反正第二个语言成熟后, 第一个语言和它的编译器是可以舍去的,它只要能编译出可执行程序就行了,我可以先写出个简单能用的编译器, 并不需要创造出非常复杂, 功能全面的编译器软件工程,
比如基本的, 流程控制解析, 函数解析 ,

我设想的是 [表] 语言.
[表格] 语言, 经过研究, 我发现所有一切都可以用表格来表示,
流程控制可以是一个表格,
函数也可以是一个表格,
并且 ,表格也可以很好地表示 '某一个' 过程,
我发现 ,不管什么风格的编程范式, 其编码都需要一个"过程".并且, 表格也能很好地展示 -数据结构.
我最近在学 HTML css javascript 我发现这些语言经过抽象, 就是个表格,
我设计的是, 把形与神 ,结合在一起,编码就是填表.
最近在研究HTML + CSS + JS,即可以做前端, 又可以做后端.
我想的是, 怎样将它们的优势抽象并综合起来.
https://movie.douban.com/subject/26718838/  [异星觉醒] 中的生物, 就像这样.
其 [神经] [肌肉] [骨骼] 不像人类一样分离,  而是融合在一起, 人类需要三种细胞去完成相对应的功能, 但是这种生物只需要一种细胞就能完成.

**Comment by nobodxbodon** [comment]
@qwas982 请把你的新思路比如https://github.com/program-in-chinese/overview/issues/33#issuecomment-332104722 发表在你的专题贴里. 因为那个帖子的目标已经变得很小, 局限性很大, 恐怕很难把你的思路融汇进去.

**Comment by qwas982** [comment]
@nobodxbodon 哦,说的也是

**Comment by qwas982** [comment]
@nobodxbodon 好,昨天遗精了,导致我理解力下降,抱歉抱歉.

我观察过现在比较接近人类自然语言的程序语言几乎都是类虚拟机语言,都建立在虚拟机基础上,如果是面对现实的前提的话,我觉得我们的方向应该一致为---[在某一虚拟机语言的基础上构建或修改],现在中文编程社区成员的方向普遍不一致,并且,成员们的水平参差不齐,不如分配下任务,大佬做后端,菜鸟丰富前端.不知您意下如何?像你和@nobodxbodon @swizl 都有一定的程序语言功底.你们都会java或其他某种虚拟机语言,所以请你们创造DSL,面对菜鸟的语法糖部分做成一个或多个接口,既能兼容汉语 中文或亚洲文字,又能兼容英语西文拉丁语系.在不同的语言文化里,可能词法和语法不尽相同,但语意是相同的,比如;

这是一个苹果
This is an apple
これはリンゴです
Das ist ein Apfel
Это яблоко

虽然[形]在改变,但[神]不变,都是表示一个意思,语意是相同的.因此也可以相通,题外话,我仿佛看到了通过借助计算机实现在人类个体间使用心电感应一类的交流或沟通方式.
这个接口看起来就像这样;
------------------------------------ ↓ ← ← ←←←←←←←←←←语言字符A←←←自然语言A
------------------------------------ ↓
{[X]VM}←←后端←←←← 语法糖 ○ 接口←←←←←←←←←←←←←语言字符B←←←自然语言B
------------------------------------ ↑
------------------------------------ ↑ ← ← ←←←←←←←←←←语言字符C←←←自然语言C

"○"是一个类似路由表的交换机或路由器的存在.
我想的这个思路是引用---前段---中段---后段---这种模式再进行二叉图分解设计,或者说构建更多的过渡带.

                                         ---(前段)---中段---后段---
                                             ↓
                               ( ---(前段)---中段---后段---)
                                    ↓
                        (---前段---中段---后段---)
刚开始不需要考虑效能等问题,只要能实现这一功能就行,首先,需要"有".这是基础.

**Comment by qwas982** [comment]
@nobodxbodon 怎么创造一门jvm语言?我需要那些条件?获得那些资料?java的基本语法我知道,其他的,比如库,模板等,完全未知.我还需要掌握哪些东西?
是仿照现成的已有某一jvm语言,比如Jython和JRuby,Clojure的实现去临摹一个吗?学习其源代码?

**Comment by nobodxbodon** [comment]
我知道的从头开始创造一个语言的教程是"两周自制脚本语言",也是用的Java.  我自己烂尾的实践在: http://tieba.baidu.com/p/4563689271

**Comment by qwas982** [comment]
现在,我觉得需要开会讨论 怎么定义语法和关键字了.如何  at @  组里的成员来商议?
毕竟,采用的词汇没有达成共识就没有公信力.

**Comment by nobodxbodon** [comment]
建议先说说你的具体设想, 有兴趣的自然会跟进. 这个话题非常大, 个人感觉一时不知从何谈起. 用词和语法可能还是其次, 决定这个语言的用途和面向用户恐怕是第一步. 另外, 之前的https://github.com/program-in-chinese/overview/issues/11 搜集了一些对新语言和编程环境的看法.

**Comment by qwas982** [comment]
哦,我用表的方式回答吧.

 用途:开发自动化软件.
 面向用户群:中文编程,初学者,转业人员.
 用词:常用动词和名词.
 语法:半自然语言化.综合各种范式的优点.

不用纯粹地代码化,而是偏形式化.多用[表,树,图]等方式建造代码.

**Comment by nobodxbodon** [comment]
> 用途:开发自动化软件.

好像所有软件都是在自动化某些工作/任务. 这里的"自动化"有什么特别涵义吗?

> 面向用户群:中文编程,初学者,转业人员.

这些用户主要会用这个语言来做什么呢? 或者说你希望他们用它做什么?

> 语法:半自然语言化.综合各种范式的优点.

哪些优点呢?

> 不用纯粹地代码化,而是偏形式化.多用[表,树,图]等方式建造代码.

用表/树/图是想要让模块之间的数据流向更加直观吗? 还是针对代码的过程逻辑? 可以举个例子吗?

**Comment by qwas982** [comment]
1,人类所谓的并行,是伪并行,人类所谓的串行是真串行.而自然界中的并行,是真并行,而串行,就是伪串行,因此人类目前创造的自动化是伪并行,我希望设计的自动化是达到伪串行的程度.
2,建造汉语编程体系.将程序与机械自动化结合.我希望他们进入编程的世界,同时付出的成本极低甚至不需要成本,就像90年代想上网是一件极其昂贵和困难的事,但现在到处都有WiFi,上网的成本已经降为零.
3,比如OO面向对象,函数式,逻辑式,编程语义化.
4,我设想的是,因为底层已经不需要去考虑,我们只要写一个类似路由表的路由器的存在,就像解码器一样,源代码根据表中的已有模块或框架用树组织,用图遍历,最后组成一句一句的语义,然后转换为字节码,送到后端编译或解释执行.此法主要是利用人的空间想象力和逻辑形式流.将抽象的东西用形象的方式表达.是什么就是什么,就像镜子.
我们不需要一开始就把表造的全面完整囊括一切.我们只需要造基础的.就像@wkgcass说的**"应当在语言做完后，再用这个语言来写后续部分"**  .以后其他开发者 使用者创造的新的代码可以成为表的一部分,这样,表就会无限的增大全面,最终覆盖一个种族的文化所有面.

**Comment by nobodxbodon** [comment]
> 1,人类所谓的并行,是伪并行,人类所谓的串行是真串行.而自然界中的并行,是真并行,而串行,就是伪串行

这里的四个概念，真并行，伪并行，真串行，伪串行，能否解释一下？或者分享一下出处。

> 2,建造汉语编程体系.将程序与机械自动化结合.我希望他们进入编程的世界.

那么主要是作为教学语言吗？类似于Basic或者Logo

> 3,比如OO面向对象,函数式,逻辑式,编程语义化.

逻辑式是指类似prolog的逻辑编程吗？ 它和函数式语言相去甚远吧。想象不出如何结合。编程语义化指的是类自然语言吗？

4,我设想的是,因为底层已经不需要去考虑,我们只要写一个类似路由表的路由器的存在,就像解码器一样,源代码根据表中的已有模块或框架用树组织,用图遍历,最后组成一句一句的语义,然后转换为字节码,送到后端编译或解释执行

在下愚钝，没看出和现在的编译器实现方式有何区别，请明示一下？

**Comment by qwas982** [comment]
1,并行(xing),串行(hang),顾名思义,多个同时进行,单个进行.伪就是假,不显现,真就是直观,直接,没有中介.我是站在人类视角的角度得出人类是伪并行真串行的,这是根据参照者与参照物的相对性而得出结论.如果站在自然界的角度就是真串行伪并行.人类和自然界是参照者与参照物.个人见解.
2,不是,是作为一门实用的语言,可以当做称手的工具.
3,函数式和逻辑式在形的方面有一定的相似性.取形的直观,将神有机结合在一起.语义化就是欲实现半自然语言化.
4,哦,这就是编译器的工作方式和原理吗?我只是希望这个语言像外内核一样,语言本身和其扩张后的增量是平行的.

**Comment by nobodxbodon** [comment]
https://github.com/program-in-chinese/overview/issues/35
