### ISSUE TITLE
基于现有语言的语法, 实现一个对应的中文版本

### ISSUE THREAD

**Issue by nobodxbodon** [program-in-chinese/overview#36]
@farteryhr 源自https://github.com/program-in-chinese/overview/issues/3#issuecomment-336719169:

> 盯死一个语言的核心语法bnf，掏出antlr做一个完全对应中文版，中文parse ast生成对应语言代码，我觉得都是很好的成果。

哪个语言比较合适呢? BTW好像你还没加入组啊?

**Comment by nobodxbodon** [comment]
本以为是单纯的关键词替换, 不过https://github.com/program-in-chinese/overview/issues/3#issuecomment-336725606 听起来更像是类似于CoffeeScript之于JavaScript. 这个设计量就上去了.

**Comment by swizl** [comment]
C语言有一个基于tinycc的小成品 
C++打算基于clang做一个。

**Comment by nobodxbodon** [comment]
@farteryhr 现在看来和https://github.com/program-in-chinese/overview/issues/25 的目标类似. 如果我的理解有误, 或者你设想的方式方法不同, 请重开此贴.
