### ISSUE TITLE
请自荐: 讨论组管理员

### ISSUE THREAD

**Issue by nobodxbodon** [program-in-chinese/overview#38]
欢迎熟悉讨论组事务, 对[社区守则](https://github.com/program-in-chinese/overview/blob/master/CODE_OF_CONDUCT.md)以身作则的组员自荐.

除了日常管理社区讨论和代码库/wiki之外, 现在想到的职(琐)责(事):
- 维护[讨论组对外网站](https://github.com/program-in-chinese/team_website)的内容
- ~~每周编写[周报](https://github.com/program-in-chinese/overview/blob/master/docs/index.md)~~
- (不)定时[备份](https://github.com/program-in-chinese/backup_issues)讨论
- 在其他社区/库发现潜在组员时发起交流/邀请

自己的一些希望:
- 最好有(广义的)中文编程实践经验
- 最好有公开的(开发员)社区/讨论群管理经验
- 至少在刚开始的一段时间和本人有线下沟通(见面 & 电话). 理想情况是人在美西时区/湾区--**不强求**

**Comment by absente** [comment]
我可以抽时间来整理知乎相关的评论讨论，其他的暂时好像没时间。人在深圳，目前下半年比较忙。

**Comment by absente** [comment]
@nobodxbodon 话说可以申请github的管理权限，但是只负责扩招人员之类的嘛？维护周报什么的目前还有点忙不过来

**Comment by nobodxbodon** [comment]
@absente 当然可以. 周报已暂停更. 可以考虑在[碰头会](https://github.com/program-in-chinese/overview/issues/66#issuecomment-407270013)机制建立后写简报.
抽空可以聊聊. 另外请审阅 https://github.com/program-in-chinese/overview/pull/73
多谢.

**Comment by absente** [comment]
@nobodxbodon 了解
PR已审阅 https://github.com/program-in-chinese/overview/pull/73

>大概看了下没啥问题。关于对外，我总结下来，大部分人的偏见就是认为所有的中文编程都是易语言那个套马甲的套路，觉得这种翻译工作（中文->英文代码->字节码/二进制机器码）没有必要。我觉得对外的工作方面，可以考虑让他们见识见识更实用，更多样化的中文编程（比如 #72 里面提到的那个zhihu的中文SQL的例子，我觉得就很有代表性，且具有一定的说服力）。

**Comment by nobodxbodon** [comment]
在开展推广之前, 先盘点总结一下一年来组内成员进行的项目吧, 对讨论组的历史和其他成员应该会有更多了解. 之前在[首页](https://github.com/program-in-chinese/overview)做了个帖子索引. 在[知乎专栏置顶](https://zhuanlan.zhihu.com/p/30882225)也有个文章索引. 
起头在[此](https://github.com/program-in-chinese/team_website/pull/14). 全组一同完成后发在专栏.

**Comment by nobodxbodon** [comment]
已更新顶楼. 鉴于在repo首页有醒目链接, 虽然暂时关闭此帖, 但欢迎任何有意自荐者随时重开此帖并自述.

**Comment by nobodxbodon** [comment]
@program-in-chinese/all 已请 @cflw 成为管理员，他的自我介绍[在此](https://zhuanlan.zhihu.com/p/92865753)。
入组以来在中文编程实践、编写[专栏稿件](https://www.zhihu.com/people/cflw/posts)、搜集相关信息、促进各方交流等等各方面一直的努力有目共睹。还望携手共进！
