### ISSUE TITLE
编写操作系统原型

### ISSUE THREAD

**Issue by nobodxbodon** [program-in-chinese/overview#43]
在写[这个](https://www.zhihu.com/question/37178794/answer/254274756)回复的时候想到如何用最小的代价用中文命名编写代码, 实现一个操作系统原型, 以迈出第一步. 最好是易于参与开发, 不需特定硬件环境. 短期目标是用于学习和实验.

看到[基于Java的操作系统发展史](http://blog.csdn.net/fasttalk/article/details/284637), 开始颇兴奋, 但后发现ARM已经在2011后[不支持byte code](https://en.wikipedia.org/wiki/ARM_architecture#Thumb_Execution_Environment_.28ThumbEE.29). 

即便如此, 仍先挖个坑, 以便有兴趣者探讨. 也可以汇聚一些中文开发者开源的操作系统原型.

**Comment by kenpusney** [comment]
不如首先用八卦替代二进制吧。

**Comment by nobodxbodon** [comment]
@kenpusney 在下对八卦不是很了解. 看起来八卦的阴阳和二进制是同一思想吧.

**Comment by zaoqi** [comment]
我計劃編寫一個函數式的中文的操作系統

**Comment by nobodxbodon** [comment]
@zaoqi 非常期待! 请问可以先分享些具体思路吗? 如打算针对何种环境(硬件/模拟器)等等?

**Comment by zaoqi** [comment]
@nobodxbodon 我將先在Javascript上實現，然後在各種硬件上實現

**Comment by bctnry** [comment]
@zaoqi 具体是要怎么做？

**Comment by bldght** [comment]
操作系统的功能主要有：进程管理、内存管理、文件系统、网络通讯、安全机制、用户界面、驱动程序
要想实现完全的中文化，前提条件是，有一套完整的中文编程工具链，然后用逐一实现上面的系统功能。

**Comment by absente** [comment]
> @kenpusney  不如首先用八卦替代二进制吧。

我倒是觉得，前苏联的平衡三进制比八卦更实用，而且更兼容六十进制。

**Comment by nobodxbodon** [comment]
如有兴趣/进展或发现相关项目(国人开发的操作系统习作应有不少, 如https://github.com/TakefiveInteractive/TedkOS , 但中文命名尚未发现) , 请重开此贴.
