### ISSUE TITLE
中文编程历史

### ISSUE THREAD

**Issue by bhuztez** [program-in-chinese/overview#47]
假如不拘泥于认为只有有了电子计算机才可以编程的话，不妨认为[九章算術](https://zh.wikisource.org/zh/%E4%B9%9D%E7%AB%A0%E7%AE%97%E8%A1%93)中的术曰...也是程序。

[APL](https://en.wikipedia.org/wiki/APL_(programming_language))家族发展到后期，是以[Tacit](https://en.wikipedia.org/wiki/Tacit_programming)风格为主的。因为ASCII字符实在太少，[J](http://code.jsoftware.com/wiki/NuVoc)代码约等于没法看，而且 +: *: 这种自加，自乘，就可以表示了，没必要弄个特殊符号。那个求平均数的代码，大致上和中文平常的说法是一致的。

[易语言](http://www.dywt.com.cn/index.htm) 指出了解决输入的问题思路，也就是智能提示得和输入法整合到一起。

**Comment by nobodxbodon** [comment]
多谢介绍. Tacit风格和函数式语言联系很大啊. 知乎上有个回答里有好像70/80年代的一个国内的中文语言设计一时找不到了, 不过很可能没有商用. 还有[这里](https://zh.m.wikipedia.org/wiki/%E4%B8%AD%E6%96%87%E7%B7%A8%E7%A8%8B%E8%AA%9E%E8%A8%80)的列表.
确实输入和提示结合会方便很多. 之前组里有[类似](https://github.com/program-in-chinese/overview/issues/11#issuecomment-320431936)的工具(vscode插件).

**Comment by kenpusney** [comment]
@bhuztez 我觉得九章算术的做法挺靠谱的毕竟古汉语（文言）可以算是综合语，有稳定的连词助词和介词来给语法框架，但是用现代汉语的这堆building block简直就是要命啊。

**Comment by kenpusney** [comment]
这就扯到了另外一个问题。

学习古汉语和学习英语哪个成本更高？

**Comment by nobodxbodon** [comment]
@kenpusney 个人觉得楼主不是拘泥于用古汉语语法设计新的编程语言.

**Comment by nobodxbodon** [comment]
@bhuztez 看到你的[最近文章](https://zhuanlan.zhihu.com/p/33248556), 请问有没打算对这种语法进行具体描述?

**Comment by bhuztez** [comment]
@nobodxbodon 语法是靠不断写比之前大一点点的程序改进出来的，而不是凭空设计出来的

**Comment by nobodxbodon** [comment]
@bhuztez 同意. 文章中的可以说是第一步吗?

**Comment by nobodxbodon** [comment]
如有兴趣请重开此贴.

**Comment by absente** [comment]
这一块有兴趣重新整理一下， 遂重开此帖

**Comment by nobodxbodon** [comment]
请在开始实施时重开此贴.
