### ISSUE TITLE
单字富指令型中文（还加韩文）编程语言 Sclipting

### ISSUE THREAD

**Issue by farteryhr** [program-in-chinese/overview#50]
https://esolangs.org/wiki/Sclipting

Sclipting is a stack-based golf language, inspired by GolfScript, that uses Chinese characters for instructions and Hangul syllables for data (strings and integers). The basic idea is that to minimise the number of characters in a program, the language should provide as many single-character instructions as possible. It was invented by Timwi in 2011.

Sclipting is not considered finished as it can trivially be extended with more and more instructions assigned to new Chinese characters.

这个方向如何【逃

**Comment by nobodxbodon** [comment]
多谢引荐！这里是它的开源ide（同作者）：https://github.com/Timwi/EsotericIDE/。好像没有看到这个语言的实现, 也许还处于设计阶段?
乍一看，它的中文字符选择有些奇妙，比如那些[化学元素的字符](https://esolangs.org/wiki/Sclipting#Instructions_to_operate_on_a_specific_index). 它的单字作为关键字的思路也许@swizl 会比较有兴趣?

**Comment by swizl** [comment]
有一些字可以借鉴，但是这个没法成生产工具。感觉比 Brainfuck、Whitespace 更反人类。

**Comment by DonaldTsang** [comment]
@swizl Sclipting就是中文版的Haskell/Lisp
