### ISSUE TITLE
vsc插件实现拼音输入法

### ISSUE THREAD

**Issue by nobodxbodon** [program-in-chinese/overview#53]
源自https://github.com/program-in-chinese/overview/issues/52#issuecomment-355761131. @htwx 辛苦! 我之前略微尝试了vsc语言服务器实现自动补全, 结果连完整的演示都没跑出来 :< 非常期待你的分享! 如果你没空, 到时我可以写篇专栏文作介绍.

看到每个词语确定用的空格也被输入了, 这个不会影响使用吗?

**Comment by nobodxbodon** [comment]
@farteryhr 新开此贴讨论这个插件. 省得那个帖歪楼 :) 
> 更需要的还是把标识符的首字拼音提出来匹配（我还没看过vscode的API，这个获取可用标识符列表应该是自动补全的核心吧，库应该有提供吧）

为了尝试自动补全, 之前看了点[官方文档](https://code.visualstudio.com/docs/extensions/example-language-server#_adding-additional-language-features), 好像在提示时默认是英文字符匹配, 还没琢磨出怎样匹配拼音输入. @lightrabbit @cleverdango 

> 至于首次输入我觉得……还是交给拼音输入法吧……

个人觉得, 短期内借助外部输入法也许是权宜之计. 但在IDE中集成输入法在长远来说还是很有价值的, 代码输入的很多辅助功能感觉最好是由IDE自带的输入法集成(最直接的比如中文关键字在字库中排列靠前等等), 毕竟外部各种输入法参差不齐, 很难顾及全部.

**Comment by htwx** [comment]
vscode 有完善的 插件系统 专门针对各种编程语言的 所以 智能感知 很容易实现的 现在 微软开源了 语言服务 和 语言服务客户端 写个 智能提示 不是大问题

**Comment by nobodxbodon** [comment]
@htwx 请问最近有何进展? 如果有可能的话, 希望早日开源, 以便其他有兴趣的成员跟进.

**Comment by htwx** [comment]
最近正在 翻译支持库 输入法 我是用 CTS 开发的

**Comment by htwx** [comment]
这几天 我发到这里来

**Comment by htwx** [comment]
![temp2222](https://user-images.githubusercontent.com/6562192/35393002-a721e164-021e-11e8-939e-4dc965668480.gif)
![temp22](https://user-images.githubusercontent.com/6562192/35393413-d9c2be26-021f-11e8-9981-f14839ac341a.gif)

**Comment by nobodxbodon** [comment]
大赞！这几天尽快试用。辛苦啦！

**Comment by htwx** [comment]
今天网络不好啊 初始个库怎么这么慢

**Comment by nobodxbodon** [comment]
初始库？是说git init吗？

**Comment by nobodxbodon** [comment]
@htwx 刚试着在vscode里运行, 这里的调试输出有些不同:
![screen shot 2018-01-27 at 1 51 33 pm](https://user-images.githubusercontent.com/392497/35476721-72351312-0369-11e8-872a-8871dc50e375.png)
选择继续运行后, 在"主程序.cts"中输入英文(比如'daoru'), 但都没有弹出自动补全. 请问这个插件需要什么外部依赖吗? 比如安装CTS?

**Comment by lightrabbit** [comment]
CTS是一个单独的项目吗？看起来好像是把TS中的标识符给中文化了？

**Comment by htwx** [comment]
这个 不是cts的插件是  输入法插件的 服务端部分 cts的 拼音 补全是 cts 语言服务插件里面实现的

**Comment by htwx** [comment]
cts 是 汉化版本的 ts  从 编译器 到 ide 插件

**Comment by htwx** [comment]
你看看 词库文件是不是 没带上

**Comment by htwx** [comment]
![bg_3ss7n 9tu g 98k rya](https://user-images.githubusercontent.com/6562192/35479167-6f31e2fe-042b-11e8-9226-48a2b9d281be.png)

**Comment by nobodxbodon** [comment]
@htwx 不好意思竟然错过了帖子更新!  词库好像都在:
![screen shot 2018-01-31 at 10 08 47 am](https://user-images.githubusercontent.com/392497/35639362-dd502530-066e-11e8-811b-4fe3f5207677.png)

刚试着调试, 好像在判断是否全拼的时候出了问题, 导致最后用了h'g搜索:
![screen shot 2018-01-31 at 10 00 33 am](https://user-images.githubusercontent.com/392497/35639372-e4430844-066e-11e8-9974-626d97be2cfb.png)

**Comment by nobodxbodon** [comment]
@htwx 继续调试如下(未完). 不知是否对诊断有用. 另外, 不知cts或者ts一般如何编写测试用例?

![screen shot 2018-01-31 at 7 48 35 pm](https://user-images.githubusercontent.com/392497/35661856-c8140aa0-06c9-11e8-9a4f-b5d94f0467d9.png)
![screen shot 2018-01-31 at 7 51 48 pm](https://user-images.githubusercontent.com/392497/35661863-cdd87cbe-06c9-11e8-826e-419b4b5b3ad1.png)
![screen shot 2018-01-31 at 7 54 39 pm](https://user-images.githubusercontent.com/392497/35661865-d226bede-06c9-11e8-89fe-0a74bd118ca4.png)
![screen shot 2018-01-31 at 7 56 34 pm](https://user-images.githubusercontent.com/392497/35661866-d2441d1c-06c9-11e8-8620-63db7866d0f0.png)
![screen shot 2018-01-31 at 7 57 04 pm](https://user-images.githubusercontent.com/392497/35661867-d260a9dc-06c9-11e8-8e62-dd77fff1e255.png)
![screen shot 2018-01-31 at 7 57 44 pm](https://user-images.githubusercontent.com/392497/35661868-d27d2364-06c9-11e8-9d7e-08b1fa1b8aa0.png)
![screen shot 2018-01-31 at 7 58 15 pm](https://user-images.githubusercontent.com/392497/35661869-d29d797a-06c9-11e8-9bcd-e7ea617b52df.png)
![screen shot 2018-01-31 at 7 58 56 pm](https://user-images.githubusercontent.com/392497/35661870-d2b41798-06c9-11e8-962c-efacc77c848c.png)
![screen shot 2018-01-31 at 8 04 06 pm](https://user-images.githubusercontent.com/392497/35661871-d2d28d7c-06c9-11e8-836d-9d189aae5406.png)
![screen shot 2018-01-31 at 8 04 38 pm](https://user-images.githubusercontent.com/392497/35661873-d2ec6ac6-06c9-11e8-94a4-292ad95c7e86.png)

**Comment by nobodxbodon** [comment]
@htwx 调试进展: 初步确定是由于在[分行读取词典文件时](https://github.com/program-in-chinese/CTS_Typewriting/blob/master/%E6%BA%90%E7%A0%81/%E6%95%B0%E6%8D%AE%E8%AF%BB%E5%8F%96.cts#L521), 使用了"\r\n"分割, 但是(猜测是由于git上传时去掉了"\r")我本地的词典文件行末只有"\n". 导致"基础词库"完全没有被读入.

**Comment by htwx** [comment]
你是什么系统? 现在是输出前5个词 可以输入 加减号.

**Comment by htwx** [comment]
![9q 6 9728hjx_3 f 7k3t6k](https://user-images.githubusercontent.com/6562192/35761857-d8f45c02-08c8-11e8-837e-926d916736d8.jpg)
![e6 _e1qhy _8cp k7 6 v](https://user-images.githubusercontent.com/6562192/35761858-d9387702-08c8-11e8-9c84-85ea614df6cd.jpg)
![f 8d k27k 17vs x uw9](https://user-images.githubusercontent.com/6562192/35761859-d97f7e04-08c8-11e8-874a-38299d58aa44.jpg)

**Comment by htwx** [comment]
![Uploading T[DG][(5XZDCZW[B41ZET@C.jpg…]()

**Comment by htwx** [comment]
![t dg 5xzdczw b41zet c](https://user-images.githubusercontent.com/6562192/35762002-96735fb6-08ca-11e8-9bcf-29d6caf50783.jpg)

**Comment by nobodxbodon** [comment]
加减号的意思是? 为避免这帖太长, 在[项目](https://github.com/program-in-chinese/CTS_Typewriting/issues)里提了对应的两个问题([读取词典](https://github.com/program-in-chinese/CTS_Typewriting/issues/3), [返回5个](https://github.com/program-in-chinese/CTS_Typewriting/issues/2)).

**Comment by nobodxbodon** [comment]
也许可供参考, [ローマ字入力時の日本語識別子入力補完プラグインの 開発](http://jssst.or.jp/files/user/taikai/2017/FOSE/fose3-1.pdf)开发了辅助插件以改进IDE对输入日语命名的支持:
> In this research, we develop a plug-in that reduces the burden on programmers when input Japanese identifier. The complication of software development projects in recent years has increased the time cost of maintaining software. So it is important to increase the readability of source code in order to reduce costs. There are several reports that it is useful to write the identi er names of variables and functions in Japanese as one way to increase the readability of source codes. However, when input Japanese identifier, there are some problems to struggle for programmers: the character conversion is troublesome and the input completion is not effective. In this research, we attempt two kinds of methods, one using Migemo and one using morphological analysis, to develop a plug-in that realizes incremental search for Japanese identi ers even if Romaji input mode, and to solve above problems.

**Comment by nobodxbodon** [comment]
源自[此问](https://www.zhihu.com/question/316530679/answer/640177016), 发现这个JS实现的本地输入法: [sxei/pinyinjs](https://github.com/sxei/pinyinjs), 也许可参考其字库和实现.

**Comment by nobodxbodon** [comment]
@lsby 先把参考资料留着：
https://github.com/zyctree/vscode-google-pinyin

另可参考易语言内置输入法功能：
![输入法_易语言](https://user-images.githubusercontent.com/392497/87242003-9ac4d100-c3dd-11ea-9731-8aaff4f6086f.png)
待确认问题：
- 是否/如何与 IDE 的补全功能集成，比如选字等等
- 中英混输比如`get名称`

**Comment by nobodxbodon** [comment]
@lsby 已于 [此插件](https://gitee.com/Program-in-Chinese/vscode_Chinese_Input_Assistant) 实现拼音输入。
