### ISSUE TITLE
我實現了一個中文的簡單的Lisp

### ISSUE THREAD

**Issue by zaoqi** [program-in-chinese/overview#56]
https://github.com/the-language/the-language
http://语.ml/

**Comment by zaoqi** [comment]
Lisp太強大了，可能會導致中文編程的分裂

**Comment by nobodxbodon** [comment]
多谢介绍! 请问有没有类似入门教程或者介绍的文章(面向新手)?
@NER000 也开发过一个类Lisp语言(https://github.com/program-in-chinese/overview/issues/33#issuecomment-329071266).
"中文編程的分裂"不知从何谈起? 个人觉得在语言设计上, 肯定会有不同的思路. 英文编程语言也有成百上千种吧. 只要互相借鉴学习可以促进整体提高, 个人觉得大可以百花齐放哈.

**Comment by zaoqi** [comment]
@nobodxbodon <The little schemer>是一本關於Scheme的書，可以模仿<The little schemer>

**Comment by zaoqi** [comment]
我將會實現一些語法 含English

**Comment by zaoqi** [comment]
@nobodxbodon 現在它的包管理系統沒設計好，沒法開始用

**Comment by nobodxbodon** [comment]
@zaoqi 
> 是一本關於Scheme的書

请问书名?
> 現在它的包管理系統沒設計好，沒法開始用

也许这个优先级比较高?

**Comment by zaoqi** [comment]
@nobodxbodon 《The little schemer》

**Comment by zaoqi** [comment]
@nobodxbodon 
优先级最高的是教育
+ 中国的教育导致我在某些时候不能做某些事
+ 我发现C++是特长 Lisp不是特长（某些政府和学校规定的）
+ 杭十五中西溪中学违反了一些规定 最近似乎违反的更加严重了

**Comment by absente** [comment]
补充一下个人观点，中文更适合组合子逻辑，即APL族的风格，lisp族的风格个人觉得比较局限，不过只要能解决问题，都是好的。

**Comment by zaoqi** [comment]
很久前被重写了。
