### ISSUE TITLE
天生支持i18n的程序语言汇总

### ISSUE THREAD

**Issue by dou4cc** [program-in-chinese/overview#59]
欢迎补充

**Comment by nobodxbodon** [comment]
不知你指的"天生支持"是指...?
如https://github.com/program-in-chinese/overview/issues/44#issuecomment-380541648 提到, 感觉汉化现有英文编程语言就是一种国际化(同理可以将关键词换为其他自然语言). 
 之前 @swizl 的实践有:
-   [为clang添加中文关键字](https://zhuanlan.zhihu.com/p/31158537)
-    [为Python添加中文关键字](https://zhuanlan.zhihu.com/p/31159526)
-    [为GCC添加中文关键字](https://zhuanlan.zhihu.com/p/31376652)

**Comment by nobodxbodon** [comment]
> 你拉倒吧

请详述你设想的语言语法(或者示例代码).

**Comment by nobodxbodon** [comment]
之前有位提到的[babylscript](http://www.babylscript.com/index.html), 应该符合要求. 有多种语言关键词[翻译](http://www.babylscript.com/translations.html)

**Comment by dou4cc** [comment]
谢谢分享. 我想要的就是这种.

**Comment by swizl** [comment]
这也是我有过的一个想法。IDE或工程软件将变量名、函数名、类名、宏、枚举等等符号提取，生成pot文件和po文件。根据语言设置，关键字读内置表，符号读po文件，动态显示。

**Comment by nobodxbodon** [comment]
@swizl 有没有可能分开两步实现. 先通过比如IDE插件来实现关键字的多语言切换. 工作量似乎相对较小.

不过不清楚如何识别&动态替换代码中的关键字部分 @htwx 请问有什么建议吗?

**Comment by swizl** [comment]
其实最开始我想的是如何汉化大型工程，扫描所有源文件，替换关键字和提现符号表，替换输出到新的目录。
其实都是字符串检索、记录、替换。
IDE多语言显示，得看IDE的高亮接口是否允许将文本替换显示。而写IDE插件我没啥经验。

**Comment by nobodxbodon** [comment]
源码翻译工具相关讨论和实践已移步 #86
