### ISSUE TITLE
提议：希望能把b大关于中文编程这块的东西做个整理

### ISSUE THREAD

**Issue by absente** [program-in-chinese/overview#63]
b大，id原名@bhuztez ，知乎大号被封，小号：[6hu2t32](https://www.zhihu.com/people/6hu2t32/activities)

其留下了很多关于中文编程的有用回答，但是大多因为其主页被封禁，已难考证。

感觉有必要做一个整理，方便以后做相关的设计参考。

**Comment by nobodxbodon** [comment]
https://github.com/program-in-chinese/overview/issues/47 是他开的. 有兴趣的话不妨整理成文, 发到专栏里.

**Comment by absente** [comment]
@nobodxbodon https://github.com/program-in-chinese/overview/issues/63#issuecomment-405849818

好的，有空会先整理到github，再整理成文

**Comment by absente** [comment]
@nobodxbodon https://github.com/program-in-chinese/overview/issues/63#issuecomment-405849818
比如这样的：
https://github.com/program-in-chinese/overview/milestone/1

**Comment by nobodxbodon** [comment]
请在 https://github.com/program-in-chinese/overview/issues/47 继续.
