### ISSUE TITLE
提问：可不可以自己创建milestone，用来归总相关issue？

### ISSUE THREAD

**Issue by absente** [program-in-chinese/overview#65]
感觉比单独开issue然后贴链接更直观。
@nobodxbodon

**Comment by absente** [comment]
就是更类似有due的收藏夹

**Comment by nobodxbodon** [comment]
细说一下? 这里主要是作为一般讨论之用, 之前的路数是, 如果项目成型了, 就新开repo, 进行专门讨论, 比如之前的junit4汉化项目https://github.com/program-in-chinese/overview/issues/10

**Comment by absente** [comment]
但是试了下好像一个issue只能放一个milestone，想想还是用其他办法实现好了。这个方法只适合分类用。

**Comment by nobodxbodon** [comment]
分类label也可以. 可以close此issue了吗?

**Comment by absente** [comment]
@nobodxbodon 嗯，label太多了不好找，发现project正合适。
