### ISSUE TITLE
讨论组成立一周年 聚会?

### ISSUE THREAD

**Issue by nobodxbodon** [program-in-chinese/overview#66]
白驹过隙, 时不我待. 
如果有兴趣的话, 要不在哪试着建个聊天室之类? 作为讨论组成员促进交流之用.

**Comment by absente** [comment]
qq群如何？比较接地气。或者gitter也行。 / 个人意见

**Comment by nobodxbodon** [comment]
之前有个qq群, 但个人平常不是很常用qq, 微信用的稍微多一点. 
在github讨论的一个好处是可以保留所有记录(这个组所有issue的备份库就在 https://github.com/program-in-chinese/backup_issues, 也备份在[osc](https://gitee.com/Program-in-Chinese/backup_issues))
gitter和stack之类的用过一点, 应该也有历史导出功能吧?

**Comment by nobodxbodon** [comment]
建议, 固定间隔(每周/两周?)选个时间大家在线, 开个类似碰头会, 开始可以试试控制在半个小时之内. 主要交流一下中文编程的相关项目/研究/推广的进展/问题, 每个问题的时间控制在几分钟之内. 如果有发现需要展开和继续讨论的, 可以直接开github issue供会后线下讨论. 否则聊天恐怕变得无的放矢. 都是忙人, 不要把碰头会变成某些不直接相关主题(比如如何学习xx语言之类)的泛泛而谈.
可以找个类似google calendar之类的来选个适合多数人的时间.

**Comment by absente** [comment]
@nobodxbodon 
嗯，那感觉还是用gitter吧。gitter的聊天历史是默认存档和开放的，应该好导出；slack没仔细用过，不清楚。

定时间的话，我建议先发起个投票，从多个渠道统计人数。人数统计好了，再定时间

**Comment by nobodxbodon** [comment]
先试一下gitter吧: https://gitter.im/中文编程/Lobby
我的时区比较麻烦, PST(还有夏令时冬令时), 最近一般晚上大约22:00-23:30 (北京时间13:00-14:30吧?), 周末还有可能15:30-16:30(北京时间6:30-7:30).

**Comment by absente** [comment]
@nobodxbodon 感觉gitter/lobby可以不定时的讨论些比较off topic的东西。如果是比较正经的感觉可以另外开一个channel

我这边的话最近都可以白天在线（UTC+8 深圳时间）

**Comment by buyouyuan** [comment]
现在都是凭着兴趣和爱好，在作中文编程这方面的事。管理员应该有个。讨论组感觉有必要，但现在力量太分散了。先搞个投票吧！

**Comment by absente** [comment]
附议投票

**Comment by nobodxbodon** [comment]
请问投票主题是?

**Comment by absente** [comment]
@nobodxbodon
 其实与其说投票，不如说是问卷调查：
- 平时的free time（固定的free time，不固定的busy time）
- 倾向于一起讨论的时间（比如具体到哪个礼拜的那一天的那个时段）
- 倾向于讨论的内容


还可以顺便统计大家认为应该优先推广的渠道（知乎，贴吧，github，豆瓣，简书，博客园，csdn，osc，infoq，图灵社区，b站，抖音，快手，微信，qq空间，qq兴趣部落，微博，饭否，天涯，水木社区，虎扑，etc.

最后还可以选填意见建议。当然，上述内容可以分开填问卷，统计时间对内就行，信息收集可以广撒网。

**Comment by swizl** [comment]
微信群?

**Comment by nobodxbodon** [comment]
@swizl 刚邀请你到gitter群了. 不好意思之前没有对组员个人发邀请函. 像 https://github.com/program-in-chinese/overview/issues/66#issuecomment-407264611 所言, 主要的考虑是聊天记录可以有存档/导出. 

不过 @absente 请问gitter如何导出聊天历史呢?
历史在: https://gitter.im/%E4%B8%AD%E6%96%87%E7%BC%96%E7%A8%8B/Lobby/archives/

**Comment by nobodxbodon** [comment]
@swizl 试试微信群吧
@program-in-chinese/all 请各位在加入时将昵称改为github账号名, 以便对号入座. ***本群仅为组内交流之用, 如有后续讨论价值的部分会整理后转到这里***
![screen shot 2018-08-14 at 11 34 03 am](https://user-images.githubusercontent.com/392497/44118212-3afb7320-9fca-11e8-949e-50f8008b78dd.png)

**Comment by nobodxbodon** [comment]
@program-in-chinese/all 现有10位组员在微信群. 打算发到无人在一周内加入为止. ***请各位在加入时将昵称改为github账号名, 以便对号入座.***
![20180908_weixin_qun](https://user-images.githubusercontent.com/392497/45258546-74abf100-b36e-11e8-8b97-d0d08458ef2c.png)

**Comment by nobodxbodon** [comment]
@program-in-chinese/all +1 -1 仍是10人. 既然还有加入的就再发一次. ***请各位在加入时将昵称改为github账号名, 以便对号入座.***
![weixin qun 0914](https://user-images.githubusercontent.com/392497/45591723-20c17f00-b90f-11e8-8a0e-7397ae73e205.png)

**Comment by absente** [comment]
现在人员已经稳定，是不是可以考虑选个日子来集中语音聊天？  @nobodxbodon

**Comment by gchihiha** [comment]
目前我作息 每天北京时间19点后 大部分情况下有空 周日休息 
提前1天确定下时间就好 我没问题.

**Comment by nobodxbodon** [comment]
@program-in-chinese/all 尝试首次微信语音群聊(现有11人, 如有未加入的说一声再重发二维码). 北京时间这周六14:00-15:00如何? 美西时间应该是周五22:00-23:00. 不知有没有其他时区的?

**Comment by nobodxbodon** [comment]
@program-in-chinese/all 为楼上的语音聚会再发一次微信群二维码. **请各位在加入时将昵称改为github账号名, 以便对号入座.**
![weixin qun screenshot_2018-11-30-01-41-22 trimed](https://user-images.githubusercontent.com/392497/49281995-ddbd7500-f442-11e8-8ac2-426831d22226.png)

**Comment by absente** [comment]
先存档，从主页的timeline隐藏

**Comment by nobodxbodon** [comment]
请各位在加入时将昵称改为github账号名, 以便对号入座.
![weixin qun 1217](https://user-images.githubusercontent.com/392497/50139943-fc4fa880-0257-11e9-8f37-79801bbe4ccb.png)

**Comment by absente** [comment]
标题改下吧。比如《组内一周年活动征集&微信群二维码&qq群
