### ISSUE TITLE
中文化 Idris

### ISSUE THREAD

**Issue by zaoqi** [program-in-chinese/overview#67]
Idris 支持中文命名，可以定义中文语法
大部分都容易中文化，除了`the`

**Comment by absente** [comment]
嗯。只是感觉idris的实用性相对欠缺

**Comment by swizl** [comment]
为啥要除了the?

**Comment by nobodxbodon** [comment]
之前 @ice1000 在Agda下的中文代码[演示](https://zhuanlan.zhihu.com/p/34805891)

**Comment by ice1000** [comment]
![](https://pic4.zhimg.com/v2-2f639f548885dfc75d9de1b3ed378263_b.gif)

**Comment by nobodxbodon** [comment]
@ice1000 呵呵还是直接贴图直观啊. 之前[楼上](https://github.com/program-in-chinese/overview/issues/67#issuecomment-411141040)引用过你的这篇文章.
惭愧Agda在Mac下环境没搭起来.

**Comment by nobodxbodon** [comment]
如有开展计划请重开此贴.
