### ISSUE TITLE
请有兴趣的自荐成为各讨论区的Collaborator

### ISSUE THREAD

**Issue by nobodxbodon** [program-in-chinese/overview#7]
由于本人才疏学浅, 希望各位能够对擅长的区域参与管理和耕耘. 如有兴趣请在这里提出, 除非其他成员提出异议, 不然都会尽快添加权限.
@sih4sing5hong5 不好意思例外一下, 没有经过同意就加你为Python区的Collaborator. 希望没有让你为难?

**Comment by nobodxbodon** [comment]
@taostein 请问有兴趣开展OCaml区吗? 在下的函数式语言经验仅限于学校的一些Scheme课程, 所以希望能够借一臂之力.

**Comment by sih4sing5hong5** [comment]
你會當參考 https://github.com/g0v/
共全部的人加入team

就免一个一个專案管理矣

**Comment by nobodxbodon** [comment]
嗯, 好主意. 刚建了 "所有人"小组, @program-in-chinese/all  应该包括了所有现有成员. 暂时所有repo有write权限. 如果觉得需要admin, 请告知.

**Comment by nobodxbodon** [comment]
暂时看来没有问题.
