### ISSUE TITLE
在国内社区进行相关推广

### ISSUE THREAD

**Issue by nobodxbodon** [program-in-chinese/overview#70]
个人对微博非常陌生. 请各位多提点. 如不方便在此, 请发知乎私信或者github公开的email.

**Comment by absente** [comment]
个人关于微博的一些相关看法

微博的历史背景：微博有很多博客时代遗留下来的早期网民，从09年到现在也快十年了，用户群体跨度很大。就技术方面来说，留下来的，也都是比较稳定的。我从12年注册微博起到现在，真正开始日常用微博应该是2015年以后，关注的人有几类，技术方面的有一类。另外我发现微博上搞网络安全的群体很固定，别的地方似乎没那么明显。

现在的微博：现在的微博主要群体应该是偏娱乐化的，如果估计个总量，女性用户应该比男性多不少。微博作为一个开放平台，对于技术推广来说还是可以利用的，但是空间不大，比较局限。比如大一点的官微，MSDN和微软亚研院这种的，关注和互动的人就多，其他都带有较强的偶然性，一般不被大v转发的东西，是没什么人互动的。因此前期运营，有必要挑选关注/互动的人的范围。

其他补充：在国内最早做microblog的不是新浪，有很多，比如饭否。个人目前啊微博和饭否都用，就活跃程度来划分，应该是：饭否>微信>知乎>豆瓣>微博>qq空间>简书>即刻>else。说来也巧，昨天在饭否提到了自己设想的中文信息化的问题，就有人私信我问是不是跟中文编程相关。然后我简单跟他介绍了一下，顺手给推了github链接和自己的微信公众号，然后他表示没有技术基础，就先不关注github了。

补充的意思在于，个人觉得做推广的化，微信公众号比知乎更划算，其次是微博。当然如果要我推广的化，我还是由小到大，先从饭否、豆瓣和即刻做起，简书跟知乎同步更新，然后是微信，最后才是微博。

**Comment by MikaGuraN** [comment]
去贴吧那些都比微博好，因为吧还有分类，微博全靠大V转发才有流量。

**Comment by nobodxbodon** [comment]
@absente 多谢详细分析.
可惜饭否暂停注册了. 简书上个礼拜试了两篇, 回复了几篇文, 感觉没什么动静. 音频的有考虑, 但投入比较大.

@MikaGuraN 贴吧感觉比较受限制, 尤其是要加外链的, 常被贴吧自动砍了, 要么就是看吧务心情. 如果要帖内容, 格式又不大搞的好(反正之前一直没有代码块格式). 另外, 总感觉那里的水和小广告很多.

其实个人觉得话语权集中在少数人这个问题在所有平台都存在.

**Comment by nobodxbodon** [comment]
简书用户名和知乎相同
bilibili用户名: bliiiilb (已投稿python入门教程之中文代码示例演示系列, [比如](https://www.bilibili.com/video/av25545719/))

**Comment by absente** [comment]
@MikaGuraN 说的基本在理，贴吧没有大v，推广比微博方便。
@nobodxbodon b站确实也是个不错的渠道，之前没算进去。另外饭否我借到一个空马甲，等下知乎私信给你

**Comment by nobodxbodon** [comment]
[微博](https://www.weibo.com/u/1460826274)开始, 暂时以中文命名为主.

**Comment by nobodxbodon** [comment]
微博账号被冻结, 似乎是被举报了. 现在报"账号异常", 需激活账号. 但手机收不到验证码..
刚看了[这个](https://www.zhihu.com/question/27424471)看来微博号风险太大. 还好就投入了一天...弃之

**Comment by absente** [comment]
@nobodxbodon 你的情况可能有点例外，微博似乎对海外ip管的比较严。我看未必是被举报的，可能是系统误判的

**Comment by nobodxbodon** [comment]
在贴吧的一些更新:
[知乎专栏"中文编程"的Python相关文章](http://tieba.baidu.com/p/5810381594)
[知乎专栏"中文编程"的Java相关文章](http://tieba.baidu.com/p/5453190155)
[知乎专栏"中文编程"的Kotlin相关文章](https://tieba.baidu.com/p/5810397697)

**Comment by nobodxbodon** [comment]
初步打算是, 新的知乎文章尽量同步到贴吧, 饭否, [OSC](https://my.oschina.net/u/750760), [博客园](http://www.cnblogs.com/program-in-chinese/). 欢迎推荐其他细分社区.
出于编辑工作量考虑也许只写简介+配图+原链接.
豆瓣/头条好像只支持国内手机?

下面的个人关注将还是中文命名的示例代码(类似[mkyong](http://www.mkyong.com/)那样的小代码片段)和[入门教程](https://github.com/program-in-chinese/overview/issues/5).

**Comment by jeffreybaoshenlee** [comment]
還有简书也可以考慮一下？

另外老吳 @nobodxbodon 可以關注一下 wordpress 博客的訪問情況，有的時候，在直連環境下，Firefox 貌似可以打開（我不確定，如果有可能的話，或許也可以考慮同步到 wordpress）。

還有就是，有沒有一種便捷的同步機制，可以把某個來源（例如 github）所發佈的內容，自動推送到不同的平臺上面（有一些這樣的插件，但是支持的平臺貌似不多，而且主要都是那種微博客型的，我覺得還是發佈中篇或長篇的博文，比較容易說清楚）

**Comment by absente** [comment]
> 豆瓣/头条好像只支持国内手机?
@nobodxbodon 这个可以找我弄。我的微信/qq = 735151965

> 還有简书也可以考慮一下？
@jeffreybaoshenlee 简书我也可以帮忙。我的简书地址是 https://www.jianshu.com/u/a18988173d4a

**Comment by nobodxbodon** [comment]
@jeffreybaoshenlee 嗯, 简书也尽量同步. 多谢提醒WP. 是用[这里](https://zh-cn.wordpress.com/)的免费版? 找了一下不少网文是从WP迁移到github pages的. [这篇](https://premium.wpmudev.org/blog/move-any-site-to-wordpress/)介绍了移到WP的一般办法.

> 便捷的同步機制，可以把某個來源（例如 github）所發佈的內容，自動推送到不同的平臺上面

很同意. 最好是脚本自动完成. 找到个[参考](https://pressable.com/blog/2013/02/07/how-to-push-code-changes-from-github-to-wordpress/), 回头试试.

@absente 这个可以找我弄

多谢. 豆瓣已经注上了, 发现一篇同道[【编程实验】一个中文的并行函数式编程语言](https://www.douban.com/note/614831239/), 但下面没有发现回复和反馈, 似乎这个话题在那里活跃度一般.
刚在头条发现了又一篇新出的水文: [如果计算机是用中文编程，你能成为计算机编程专家吗？](https://www.toutiao.com/a6582150569895395843/). 看来还是有在那里宣传的理由的.

个人的时间太有限, 还要写新内容, 希望能尽量自动化同步各平台的过程. 估计很难保持所有(甚至某一个)平台的跟踪/互动. 如果发现什么动向还请各位在https://github.com/program-in-chinese/overview/issues/3 多提醒/协调. 这帖就继续讨论各平台主动推广的问题吧.

**Comment by jeffreybaoshenlee** [comment]
@absente 看到您的簡書了，寫得很好。

@nobodxbodon 剛才測試了一下，火狐瀏覽器能夠較快打開 https 版本的 WP 網站

**Comment by nobodxbodon** [comment]
继续更新贴吧:
[知乎专栏"中文编程"的C语言相关文章](http://tieba.baidu.com/p/5815998682) @swizl 这两帖包括汉化项目
[知乎专栏"中文编程"的C++相关文章 ](http://tieba.baidu.com/p/5815996929)
[知乎专栏"中文编程"的C#相关文章](http://tieba.baidu.com/p/5816001108)  @TKT2016 主要是Z语言相关文章

**Comment by nobodxbodon** [comment]
继续更新贴吧:
[知乎专栏"中文编程"的Excel相关文章](http://tieba.baidu.com/p/5832366287)

另外, [易语言论坛](bbs.eyuyan.com)好像有几天不能访问了? 本来在那里也有专栏更新帖.

**Comment by nobodxbodon** [comment]
合并自@absente  的https://github.com/program-in-chinese/overview/issues/71:


> 豆瓣跟饭否都有api，应该也都有人写过bot，简书跟知乎尚未清楚，貌似IFTTT之类的平台，或是安卓上的tasker/xposed一类的自动化应用可以解决这个问题？

> 现在是在team_website库尽量把所有知乎文章都转到github pages上, 所以是markdown格式. 要研究一下api看看能不能方便地从markdown格式转过去. 我有个小linux机器可以跑自动任务.

**Comment by nobodxbodon** [comment]
@ZoomQuiet 请教一下关于社区建设和推广的问题. 最初在此建立讨论组的主要出发点是:
- 管理成本较小
- 面向程序员群体
- 便于分享代码
- 所有讨论内容方便导出和备份(https://github.com/program-in-chinese/backup_issues)

在讨论过程中逐渐发现这里接触不到很多中文编程的潜在用户(https://github.com/program-in-chinese/overview/issues/41, https://github.com/program-in-chinese/overview/issues/19). 请问有建议或经验可以分享吗?

**Comment by nobodxbodon** [comment]
2019年 4 月末开通["用中文编程"微信公众号和今日头条号](https://zhuanlan.zhihu.com/p/64079707)。还有其他一些自媒体号（企鹅、大鱼等等）。最近的推广相关详细数据请见公众号文章。
下一篇会报告至今的”收入”金额 ;)

**Comment by nobodxbodon** [comment]
[Gitee《开源指北 1.0》之——开源项目必须用英文命名标识符吗？](https://zhuanlan.zhihu.com/p/347701292)

**Comment by nobodxbodon** [comment]
与 #41 合并。
已有相当实践土壤。
https://zhuanlan.zhihu.com/p/123232103
