### ISSUE TITLE
关于多平台文章同步的一些思考

### ISSUE THREAD

**Issue by absente** [program-in-chinese/overview#71]
豆瓣跟饭否都有api，应该也都有人写过bot，简书跟知乎尚未清楚，貌似IFTTT之类的平台，或是安卓上的tasker/xposed一类的自动化应用可以解决这个问题？
@nobodxbodon 

https://github.com/program-in-chinese/overview/issues/3

**Comment by nobodxbodon** [comment]
源自讨论https://github.com/program-in-chinese/overview/issues/70#issuecomment-407936491

@absente 多谢. 现在是在[team_website库](https://github.com/program-in-chinese/team_website)尽量把所有知乎文章都转到[github pages](http://codeinchinese.com/)上, 所以是markdown格式. 要研究一下api看看能不能方便地从markdown格式转过去. 我有个小linux机器可以跑自动任务.

**Comment by nobodxbodon** [comment]
请在 https://github.com/program-in-chinese/overview/issues/70 继续相关讨论.
