### ISSUE TITLE
关于中文化常用DSL的一些想法

### ISSUE THREAD

**Issue by absente** [program-in-chinese/overview#72]
最近有人请教我一些问题，一类是perl的问题，涉及正则比较多；另一类是python/django的问题，主要涉及SQL/ORM。

这使我不经想把两者的核心问题关联到一起：perl的代码看不懂，主要是因为正则，而数据库这个有些人玩不转，主要也是卡在SQL这块地方。

所以既然这两种都是DSL，而且正则的特性恰恰和APL的组合子逻辑很接近，为什么不试着做一套基于中文的正则表达式规则呢？同理也适用于SQL，当然SQL的问题要更复杂一点，因为SQL涉及到数据层的通信标准，而正则只需要匹配处理字符串。

**Comment by nobodxbodon** [comment]
知乎有位在做一套中文语法的类似SQL语言: https://www.zhihu.com/question/33983820/answer/186692475

**Comment by swizl** [comment]
基于中文的正则表达式规则?能举例子吗？
我觉得正则已经跟中英文没有关系了，纯符号的了。除非你想匹配偏旁部首，但这已经不是正则该做的了。

**Comment by swizl** [comment]
当然SQL汉化我也有兴趣，但优先级排在比较后面。打算以后用mysql，试试。

**Comment by absente** [comment]
> 基于中文的正则表达式规则?能举例子吗？

这个暂时很难想出合适的例子，简单说正则的符号可读性，比APL的希腊字母还要差，还是有改进余地的。


这个帖子关于正则的内容我都是可以有空再补充想想。

-------
正则里面，.+*这种不影响，继续保留，\w这种可以替换成 `词`，\d->数，\a-zA-Z -> 全字母

**Comment by absente** [comment]
前面的关于`匹配偏旁部首`这段的内容之前没看到，感觉以后要做也可以。不过确实已经不属于标准正则需要考虑的问题了。

**Comment by nobodxbodon** [comment]
看起来已在https://github.com/program-in-chinese/overview/issues/89 继续此话题.
