### ISSUE TITLE
关于统一现有PL的中文简称及相关术语规范化的一些建议

### ISSUE THREAD

**Issue by absente** [program-in-chinese/overview#76]
>http://fanfou.com/statuses/gyFkSQjHUEI

科学用语，避免歧义，保护自然语言，从我做起：
1. 使用**编程语言**而不简称语言
2. 使用C**代码**或C，而非C语言，
3. 用**PL**缩写替代编程语言（某语言=某PL 
4. 在1的基础上，尊重现有的俗称（比如go**lang** 
5. PHP这种不需要加PL后缀的就不加 
6. 将写代码和编程**区别**开来coding!=programming

--------

相关涉及的PL不多，目前想到的只有两个：

Official | 俗称 | 建议称谓 | 保留称谓
------- | ------|------------|----------
C  | C、C语言 | C、C代码 | C语言
Go | Go语言、golang| golang|
JavaScript| JS | - |

**Comment by nobodxbodon** [comment]
> 使用编程语言而不简称语言

"C语言"之类的说法已经约定俗成, 请问为何要强调这是"编程语言"?

> 使用c代码而非c语言，

不解.

> 用PL缩写替代编程语言（c语言=cPL

有何优势?

4. 尊重现有的俗称（比如golang

这和1)原则相悖吧?

> PHP这种不需要加PL后缀的就不加

为何PHP不需?

> 将写代码和编程区别开来coding!=programming

请详述区别在哪里?

**Comment by absente** [comment]
@nobodxbodon 已更新一楼的表述。

> 使用编程语言而不简称语言

为了区分自然语言和编程语言是两种完全不同的东西。虽然英文都是language，但在汉语的语义里，英文的language并不能完全等价于中文的语言一词，在特定的场合容易产生歧义，故有此替代一说。

> "C语言"之类的说法已经约定俗成, 请问为何要强调这是"编程语言"?

关于C语言的问题，可以更尊重现有的用法。并非为了强调这是编程语言，而是为了减少语言一词的混用。

> 使用c代码而非c语言，

直接用C也可以，尽量减少使用“C语言”的语言二字。

> 用PL缩写替代编程语言

精确，且省字符。应该说建议用词的优先级是：PL>编程语言>>>语言；简称语言是不够严谨的。

另外第四点不矛盾，整个1到6是按优先顺序排列的

> 为何PHP不需?
因为当使用PHP一词的时候，如不加说明，则既有PHP编程语言的含义，也有PHP这个runtime的意思。基本上主流的除了C和Go（BASIC这些历史PL除外），目前好像大多数的编程语言，都没有直接简称某语言。

> 将写代码和编程区别开来

这个主要是个人观点。个人认为写代码只是编程的一种实现方式，而编程是程序设计的一种专用说法，即理想状态下，是可以不写代码也能编程的。但现实情况是主流的开发流程仍然将编程和写代码紧耦合，导致了平时大多数人没有将两者区分开来。

软件开发，编程，写代码，这三种应该是分开的。个人观点。

**Comment by nobodxbodon** [comment]
>>    用PL缩写替代编程语言

> 精确，且省字符。

即使国外, 只要不是专业做编程语言设计和实现的圈子, 都不大在交流中用PL代替Programming Language. 无论中英, 术语缩写(不仅是计算机术语)对于非领域内人士并不友好. 这个PL可能表示的[英文术语列表](https://www.acronymfinder.com/PL.html)有一百多项 , 可以想象它对于非同行的带来的歧义和混淆.
比较PL-Programming Language-编程语言, "编程语言"是一个简约和可读性兼顾(尤其对于非同行)的说法.

**Comment by absente** [comment]
@nobodxbodon 嗯，我的主要想法是替代掉语言二字的滥用，用编程语言是严谨也是最好的，偷懒的时候可以用PL。

**Comment by nobodxbodon** [comment]
上面的表述仍然很有争议. 
如打算将其形成规范, 需要更多客观依据(包括各种编程语言/软件工程背景知识等). 
如有兴趣将其完善/严谨化, 请重开此贴.
