### ISSUE TITLE
关于emoji符号在中文编程推广过程中潜在的辅助作用

### ISSUE THREAD

**Issue by absente** [program-in-chinese/overview#77]
在饭否跟人[讨论]中文编程的时候，又涉及到另外一个具体概念叫**文言文编程**[古文编程]。想了想，文言文毕竟不那么好学。所以为了照顾以后学不懂文言文编程的小朋友们，其实可以再加入一套emoji编程>
```
😚 heloword  #预定义😚=print

```
http://fanfou.com/statuses/HXWl5V9anqE

**Comment by absente** [comment]
当然为了更方便输入emoji，可能还要做一套针对emoji优化的输入法方案（可以基于rime）

**Comment by nobodxbodon** [comment]
如果有需要用emoji才能表达业务语义的情况, 请再开此帖。
