### ISSUE TITLE
从象棋棋谱引出的关于传统术语在中文编程领域的再利用及语法借鉴

### ISSUE THREAD

**Issue by absente** [program-in-chinese/overview#78]
引：昨天晚上偶然见随到央视的一个节目叫挑战不可能，里面有个小朋友在挑战跟人下盲棋，里面念的口令我觉得挺有意思，让我想起了早年电视剧《棋武士》里相关的棋谱口令。

> 马八进七，帅五平六。士五进六。 http://fanfou.com/statuses/K9wL1GBdb1E

类似的术语，我记得围棋也有，古琴也有，其他的就不太了解了。
感觉很适合tacit组合子逻辑的文言编程思路，具体可参考 @bhuztez 的九章算术。

**Comment by absente** [comment]
另外关于例程引经据典，其实活学活用挺好的。我看用西遊記这样广为人知喜闻乐见的題材就很好。

https://github.com/program-in-chinese/overview/issues/5#issuecomment-411248133

**Comment by nobodxbodon** [comment]
如有进一步实践计划请重开此贴.
