### ISSUE TITLE
关于C族和类C编程语言关键词的相关翻译总结和参考

### ISSUE THREAD

**Issue by absente** [program-in-chinese/overview#81]
C的有：void无，return返，int整/整4/四位/i4，float浮/单浮/f16，long长/长整/8位/i8，char字/c4，double双/双浮/d32，include含/引/包含/引含，define定/设/定义，typedef定型/类定义，if若/如果/假设，else否则/不若/另外/其他，for若/落/佛/复/多，while当/围/为真/唯，break破/过/断/开，switch分/选/验/判/如，case例/支，null空，&与，|位或，!非，=为，==等于，&&且，||或，!=不等/非同/不为，++增/升，--退/降，*=乘为，true零，false壹，~异或，>>移右，<<移左

python：def设，return回，:则，import引/引入，if如，for若，while为真，class类，as为，and和，or或，else余，elif余如/再/次，print印，None空，in因/阴/其，is是，global勾/全局，local篓/本地，with同/携，lambda拉，

**Comment by nobodxbodon** [comment]
由于主题相同, 已合并至https://github.com/program-in-chinese/overview/issues/40#issuecomment-414157031 请在那里继续探讨.
