### ISSUE TITLE
关于用单字表示常用数字的一些思考

### ISSUE THREAD

**Issue by absente** [program-in-chinese/overview#82]
众所周知，我们这个文明，除了最早应用十进制以外，历史上还有十六进制的广泛应用（半斤八两，中国算盘是十六进制兼容十进制的，日本算盘是十进制兼容八进制，俄罗斯算盘没有做进制优化）。而我国的十进制，这个进制最早并不是现在的进位制，所以没有0进位的概念，都是一十六，二十八这样。于是为了方便，古人会把一十六简作十六，二十八简作廿八。

但是30卅40卌，之后，就没有一个统一的成文说法了。百度给出的是：五十，圩； 六十，圆； 七十，进； 八十 ，枯；九十，枠。二圩，百；二百，皕。

知乎有相关的问题：除了「廿」和「卅」，十的其他倍数还有对应的汉字吗？https://www.zhihu.com/question/22406781

其他参考：【史海钩沉】从“十 廿 卅 卌”说开去◇ http://www.360doc.com/content/14/0614/22/14421628_386663312.shtml

-------

我的想法是，现有的还不够方便。应该把十到一百以内的每一个数都找一个单独的字出来（有余力的话，再扩展到360个/1080/65536个）。于是就有：

0洞
1甲一壹幺2乙二双贰两3丙三叁仨/又4丁四肆5五伍戊
6六己陆7庚七柒拐8辛八捌9九壬玖勾10十癸拾
11/土12/丰13/区14/田15/吾16/杆17/枉柴18/木19/丸20廿卄/王
27/叒
30卅丗/沤31 32 33 34 35 36
40卌/[甲]由41 42 43 44 45 46 47 48 49
50圩/梧51 52
60圆/秆叶61/吐62/吋63时64/卦旺
70进/忹汪71 72
80枯/米81/叕
90枠/执纨91 92 93 94 95 96 97
100百/井 110 111 112 113 114 115 116 117 118
128/珧桃
180
192
200皕
240
256/
300/磊
320
360 361
384
400
480
512
576
600
640
700
720
768
800
960
1000/卉
1024/果
1080/辍
1366
1920
2000
2018 2019 2020

40000/爽

65536/亜

--------

关于单字示数与中文编程的具体应用，暂时想不到特别实在的例子，只是比较符合APL的风格。2018如果按照上面的写法，用两个字[廿木]就可以了（有点那种汇编的时候，使用两个16进制数组合成一个word的感觉）。

**Comment by nobodxbodon** [comment]
> 关于单字示数与中文编程的具体应用，暂时想不到特别实在的例子

如有实例表明可以带来代码可读性或其他方面的好处, 请重开此贴.

**Comment by absente** [comment]
@nobodxbodon 目前想到一个，就是用256个字符*4个汉字，表示IPv4地址，或者用65536个字符，每个字对应一个地址

**Comment by absente** [comment]
想起来，以前的腓尼基字母/希腊字母/希伯来字母/西里尔字母/西奈字母，都是有示数的意思的。比如1-9会对应字母a-i，j往后是10/20/100/200/1000这样。
