### ISSUE TITLE
hi~我来了 我描述一下自己观点

### ISSUE THREAD

**Issue by gchihiha** [program-in-chinese/overview#84]
- 我不会在面向过程的编程方式上做改变
比如无意修改关键词写法
- 自然语言有很多快捷短语 以及灵活的用法，但我致力于剔除这些东西，目的是得到一个比较核心的部分。
推荐一本书《现代汉语800词》
- 语言可以描述思维，用图也可以。只是二者各有长短。

**Comment by absente** [comment]
@gchihiha 说来也巧，800词这本书前段时间在微信群里看人提到，自己也买了一本，挺好的。

摸个人所用的工具书里面，相关的主要有：
《四角号码字典
《八思巴字与元代古汉语
《怎样打算盘
《designing for scalability with erlang
《数学小丛书
《高等数学引论
《中国古代文化常识 - 王力
《电子设计从零开始
