### ISSUE TITLE
批量代码汉化工具

### ISSUE THREAD

**Issue by nobodxbodon** [program-in-chinese/overview#86]
源自 @swizl 的 https://github.com/program-in-chinese/overview/issues/59#issuecomment-411272880

https://github.com/program-in-chinese/overview/issues/37 中曾经用JDT实现从Java源码中类/方法的提取(似乎也有汉化后[代码生成](https://gitee.com/zhishi/JavaCN/tree/master/src/main/%E5%B7%A5%E5%85%B7/%E7%B1%BB%E7%94%9F%E6%88%90%E5%99%A8)). 另一种可能是使用Antlr分析+[StringTemplate](http://www.stringtemplate.org/)生成新代码. 
一般的源码命名汉化还需[术语词典](https://github.com/program-in-chinese/overview/issues/85)以及普通英汉词典(有库吗?).

**Comment by nobodxbodon** [comment]
发现一个[英汉词典](https://github.com/skywind3000/ECDICT)数据库, 考虑将其数据裁剪后封装成API, 可作为独立项目开展.

**Comment by nobodxbodon** [comment]
短期内考虑略过自然语言部分. 由于命名部分相对语法较简单(基本没有整句, 短语/单词为主), 继续[二楼思路](https://github.com/program-in-chinese/overview/issues/86#issuecomment-416017103)走[基于规则的机翻](https://en.wikipedia.org/wiki/Rule-based_machine_translation)

**Comment by absente** [comment]
ageByName这种翻译，感觉可以机械化，by=从，>=龄从名

**Comment by nobodxbodon** [comment]
> ageByName这种翻译，感觉可以机械化

之前也是打算用简单的语法转换, 比如`按名称取年龄`("年龄"置后)等. 个人认为不一定要保持原文顺序, 因为如果中文很难找到同样顺序的表达, 多半这种表达本身就不常用.

> 有时候英译中，中文反而没有原文直观（视觉上的，英文有大小写，容易分词）

之前写的[在代码中进行中文命名(类/变量/方法等)的优势](https://zhuanlan.zhihu.com/p/40098652)里的优势之一"不需要驼峰命名法或者下划线分隔".

**Comment by nobodxbodon** [comment]
[Generate source code from AST with Antlr4 and StringTemplates](https://stackoverflow.com/a/38245353/1536803)提到, 源码语法分析后再基于语法树生成源码这一转换过程有不少细节问题, 并非那么简单. 当然命名翻译并不牵涉改变代码结构, 但其中提到的这几条都还是问题:
> - Preserve comments. I don't think ANTLR ASTs do this.
> - Generate layout that preserves the original indentation.
> - Preserve the radix, leading-zero count, and other "format" properties of literal values
> - Renerate strings with reasonable escapes

考虑搭建原型时暂时只用最简单的字符串替换而不是对代码进行语法分析.

**Comment by nobodxbodon** [comment]
刚试了使用[词典API](https://github.com/program-in-chinese/overview/issues/88)翻译这个简单的例程:
```python
class Person:
    pass  # An empty block

p = Person()
print(p)
```
有几个发现:
- 这个词典数据中有5万多词有`[计]`的释义, 应该是计算机领域的释义. 比如`class: [计] 类别; 类; 种类; 类程`, 但也有比较偏的如`pass: [计] 遍`, `print: [计] DOS外部命令:在打印机上打印文件, 可一边打印文件一边执行其他工作`, 原型可以优先用`[计]`释义, 之后再用[术语词典API](https://github.com/program-in-chinese/overview/issues/85)进行改善.
-  由于没有语法分析, 暂不识别注释, 因此它的空格也被保留. 比如上面的`# An empty block`就被译为`# 一 空 块`
- 像`p`这样的缩写命名, 理想情况是根据上下文得出含义(person), 但原型打算暂对单字母变量直接忽略(不翻译)

**Comment by nobodxbodon** [comment]
[使用现有在线翻译服务进行代码翻译的体验](https://zhuanlan.zhihu.com/p/44169542), 最后作了一点初步的需求分析.

**Comment by nobodxbodon** [comment]
[代码翻译尝试-使用Roaster解析和生成Java源码](https://zhuanlan.zhihu.com/p/44536065). 感觉自然语言翻译部分挑战更大, 如何选择最合适的释义和词序重组等. 暂时打算先专攻Java. 其他编程语言如有类似[Roaster](https://github.com/forge/roaster)这样兼顾源码语法解析和生成的库, 烦请告知.

**Comment by nobodxbodon** [comment]
初步界面演示, jquery. 可能写篇短文. http://74.91.17.250:9000/
![screen shot 2018-09-18 at 12 30 30 am](https://user-images.githubusercontent.com/392497/45671361-1f907d80-bada-11e8-8a19-05a4dc7d0002.png)

**Comment by nobodxbodon** [comment]
语法高亮编辑器~
![screen shot 2018-09-23 at 4 35 00 pm](https://user-images.githubusercontent.com/392497/45936222-f869fe00-bf68-11e8-8359-e0ff82df7664.png)
进度说明: https://www.v2ex.com/t/484895#r_6214357

**Comment by nobodxbodon** [comment]
@swizl https://github.com/program-in-chinese/overview/issues/48#issuecomment-426504562 转至此继续探讨:

> 想了一下做成对单个源文件翻译的工具就好了。遍历文件夹用shell等工具处理就可以了。但是得保存词条表。流程大概是：先在词条表中查找，有的话，直接用，以保证整个工程翻译的一致性。没有的话，调用翻译接口，使用返回结果，并保存在词条表中。

感觉难度取决于对源代码的语法分析程度. 如果翻译出的文件需要能够编译, 就有更多细节要照顾. 像上面实现的, Integer->整数, String->字符串, 对于一般浏览代码也许有意义, 但导致不能编译. 此项目暂时的重点是阅读代码大意.

**Comment by swizl** [comment]
@nobodxbodon 哈哈，对的。
第一步，可以将所有变量名、函数名、宏名、枚举值等字符串，放在词条表里，供人校对，甚至可以作"本地化"。即使同一个单词在不同的名称中被翻译成不同的意思，对编译器也不影响，因为整个字符串在工程中是一致的。
第二步，再作分词，将各种名称、字符串，按照驼峰、下划线、空格等分词，并建立数型关联表、映射表等。确定一个元词的翻译，对应的名称串、字符串，都会翻译一致。
最后，可能再去考虑更复杂的情况：
    1. 一个词多个意思的都在工程中又体现得歧义现象，解决办法是像wiki一样，按歧义分拆关联表，所以关联表得文本化，能人工编辑。
    2.语序调整等就再说啦。

**Comment by nobodxbodon** [comment]
用了个`translate`子域名, 但还没搞定80端口, 还是原来的9000端口: http://translate.codeinchinese.com:9000/

**Comment by nobodxbodon** [comment]
已改为80端口. 刚测试 http://translate.codeinchinese.com/ 如下.
改进的功能是: 类型字段已翻译(visitedCountries->拜访国家)
![screen shot 2018-10-07 at 11 15 36 pm](https://user-images.githubusercontent.com/392497/46594290-f9ca1900-ca86-11e8-9393-ea33897b85ed.png)

**Comment by nobodxbodon** [comment]
JavaScript源码翻译可参考[JS代码翻译成中文书写的代码](https://zhuanlan.zhihu.com/p/20621085)

**Comment by nobodxbodon** [comment]
[Github代码翻译插件](https://zhuanlan.zhihu.com/p/43304088)的后续:
[Chrome插件原型](https://chrome.google.com/webstore/detail/github%E4%BB%A3%E7%A0%81%E7%BF%BB%E8%AF%91%E5%8E%9F%E5%9E%8B/inicknfojohdbgekdffgcdfiheflpnbh/related)
通过调用[离线英汉词典插件](https://github.com/program-in-chinese/webextension_english_chinese_dictionary)的查词接口, 实现了除关键词和核心API之外的命名和文本单词部分翻译:
Python:
![screen shot 2018-10-17 at 12 15 00 am](https://user-images.githubusercontent.com/392497/47069724-84f09080-d1a4-11e8-9550-89aaa582f6aa.png)
Typescript:
![screen shot 2018-10-17 at 12 36 21 am](https://user-images.githubusercontent.com/392497/47069956-106a2180-d1a5-11e8-825b-fa5a882c806d.png)
Java:
![screen shot 2018-10-17 at 12 38 24 am](https://user-images.githubusercontent.com/392497/47069960-12cc7b80-d1a5-11e8-8c47-a0f9bb0c4068.png)
打算继续改进. 包括添加所有语言的关键词词典, 等等.

**Comment by nobodxbodon** [comment]
继续下去有两个方向. 一是继续浏览器和vscode(及visual studio)上的插件开发; 二是Java开发环境下的插件开发, 比如Eclipse.
前者的优势是, 因为都是JS实现, 可以重用的部分不少. 而且面向平台和用户较广. 但JS在NLP方面的库相对较少.
后者的优势是, Java的NLP相关库较丰富, 用户群也许更接近商用项目.

初步打算, 在[v2帖](https://www.v2ex.com/t/504604#r_6405817)的三项中, 先完成vscode的源码翻译预览(效果与当前浏览器插件齐平), 以接触尽可能大的用户群. 之后再确定是进一步改进机翻效果还是尝试第二个方向.

> 几种模式都在考虑:
> - 只是预览
> - 批量翻译(只是单向)
> - 像你说的翻译后只是作为中间产物使用, 源码仍然是英文命名

> 实现优先级暂定是从上向下, 感觉技术难度也是越后越难. 理想目标是保证完全翻译出的编译无误, 但即使使用 IDE 本身的重构 API 恐怕也不能 100%.

**Comment by absente** [comment]
个人觉得和 #85 有很大部分重叠，不如先把这个item从主页隐藏了。如有新的阶段进展，再开，也许会好点

**Comment by absente** [comment]
merge <- https://github.com/program-in-chinese/overview/issues/88

**Comment by nobodxbodon** [comment]
基于https://github.com/program-in-chinese/overview/issues/86#issuecomment-436745681 的计划, 已初步完成"vscode的源码翻译预览"功能: [VS Code英汉词典v0.0.8: 批量翻译文件部分命名](https://zhuanlan.zhihu.com/p/53288297). 
vscode对源码标识符操作支持的API感觉比较有限. 机翻的挑战也不小.
短期目标转向https://github.com/program-in-chinese/overview/issues/97 .
