### ISSUE TITLE
[OT]建了一个erlang/APL微信群

### ISSUE THREAD

**Issue by absente** [program-in-chinese/overview#87]
-- 链接已删, 如有兴趣请个人联系 --

方便日常讨论交流。包括但不限于：prolog/erlang，typescript/python/perl，APL/J/K/Q，mathematica，rust/forth，haskell/racket

OT=off topic

**Comment by nobodxbodon** [comment]
既然确定与本组主题无关, 请以个人名义, 通过个人渠道进行联系.
