### ISSUE TITLE
简明英汉词典API

### ISSUE THREAD

**Issue by nobodxbodon** [program-in-chinese/overview#88]
源自 https://github.com/program-in-chinese/overview/issues/86#issuecomment-416753460

打算Java封装https://github.com/skywind3000/ECDICT 中的ecdict.csv , 如Jar包大小不会超出发布平台限制则不作数据裁剪.

**Comment by nobodxbodon** [comment]
0.0.1版发布在Maven. 源码已[入库](https://github.com/program-in-chinese/english-chinese-dictionary)
接下去尝试调用它翻译简单源码, 作为https://github.com/program-in-chinese/overview/issues/86 的第一步.

**Comment by absente** [comment]
merge <-https://github.com/program-in-chinese/overview/issues/85

**Comment by absente** [comment]
merge -> https://github.com/program-in-chinese/overview/issues/104
