### ISSUE TITLE
实现做一个Github 网站UI中文化插件

### ISSUE THREAD

**Issue by absente** [program-in-chinese/overview#90]
缘起：很多人觉得github很复杂，也有很多人觉得GitHub全是英文看着发怵，简单说，在广大国人面前，GitHub还是不够人性化，不够贴近国情。

思路：实现一个chrome的crx插件，可以覆盖大部分基于chromium和webkit/blink内核的浏览器，包括但不限于：Firefox，Opera、Vivaldi，360、qq、猎豹等

需求实现：

- [ ] 4.实现readme和issue的自动翻译功能
- [ ] 4.1实现issue comment文本框的语言转换功能（输入中文，输出英文
- [ ] 1.界面UI汉化：
- [ ] 1.1覆盖常规页面[repo/issue]
- [ ] 1.2覆盖 project/search
- [ ] 2.论坛结构优化 /简化操作逻辑
- [ ] 2.1优化code目录结构/树状浏览
- [ ] 3.优化注册和登录流程
- [ ] <del>3.1或者，使用一个公用github账号，进行游客代理</del>

（to be continue / to be done

**Comment by nobodxbodon** [comment]
之前github有过语言切换功能, 但2016年停止了: https://webapps.stackexchange.com/questions/51424/github-in-other-languages
感觉这个插件可以集成代码翻译功能: [浏览器插件实现GitHub代码翻译原型演示](https://zhuanlan.zhihu.com/p/43304088)

> 3.1 使用一个公用github账号，进行游客代理

与匿名发言类似, 容易被滥用吧

**Comment by MikaGuraNTK** [comment]
我觉得网站ui不需要翻译(
需要翻译的是项目的readme、issues

**Comment by absente** [comment]
> @MikaGuraNTK 我觉得网站ui不需要翻译(
> 需要翻译的是项目的readme、issues

对于已经会英语的来说自然是不需要UI翻译的。readme 和 issue倒是有更需要一点。(已补充到1楼

> @nobodxbodon 感觉这个插件可以集成代码翻译功能: 浏览器插件实现GitHub代码翻译原型演示

嗯，有很多现有的代码可以利用。

> 与匿名发言类似, 容易被滥用吧

是的（已排除

**Comment by absente** [comment]
Archive
