### ISSUE TITLE
以F#为主，中文化CLR

### ISSUE THREAD

**Issue by absente** [program-in-chinese/overview#98]
以.net core 2.1为本

**Comment by nobodxbodon** [comment]
和 @htwx 在[这里](https://github.com/dotnet/csharplang/issues/993#issuecomment-337291956)的思路类似?

**Comment by absente** [comment]
re: @nobodxbodon 

有点类似，不过是循序渐进，从编程语言往运行时逆推的思路。

**Comment by absente** [comment]
先挂起。有进展再开

**Comment by absente** [comment]
考虑先用ironpython实现 https://github.com/program-in-chinese/overview/issues/95
