### ISSUE TITLE
关于“中文化”和“汉化”的概念划分

### ISSUE THREAD

**Issue by absente** [program-in-chinese/overview#99]
我觉得为了与易语言这类汉化编程语言区分开来，应该赋予中文化更广的含义。即中文化不局限于关键词汉化，而是在汉化的基础上做推广。APL这类symbolic的方案，实际上是另一种中文化思路。

**Comment by absente** [comment]
举个例子。function、asynchronized、system，这三个词，汉化写作[函数，异步，系统]，中文化可以写作汉化形式，也可以缩写成[fn，async，sys]

**Comment by nobodxbodon** [comment]
"中文编程"现在比较[狭义](https://baike.baidu.com/item/%E4%B8%AD%E6%96%87%E7%BC%96%E7%A8%8B/9730041?fromtitle=%E6%B1%89%E8%AF%AD%E7%BC%96%E7%A8%8B&fromid=7661807): `中文编程（或者称为中文编程语言）是指使用中文来书写的程序设计语言，`之前小结的[四个方面](https://zhuanlan.zhihu.com/p/30882225)仍觉得都属于中文编程范畴. 

> 也可以缩写成[fn，async，sys]

不大理解如何与"中文化"联系起来.

**Comment by cflw** [comment]
我觉得“中文化”这个词只是字面意义上的文字的变化。而“汉化”不仅可以用于语言，还可以用在文化等方面，带有较重的民族色彩，就像百度百科里的解释：
> 广义上的中国化包括作为中华民族主体的汉族对周边民族的同化与融合，也被称作**汉化**。这个过程一直贯穿着中国的历史，以及民族融合的过程中。在古代，居住在中原的汉人相对周边各族，具有发达的政治经济文化，优越的地理位置，悬殊的人口优势，因而在民族融合中扮演主导角色。

所以我觉得不管是从零发明中文编程语言，还是照搬主流编程语言把英文替换成中文，都是编程中文化的体现。

**Comment by absente** [comment]
> 不大理解{缩写成[fn，async，sys]}如何与"中文化"联系起来.
@nobodxbodon 中文本质上是一种符号抽象，有象形，有会意，有偏旁部首。好处就是尽可能用少的字来抽象表达更复杂的内容。所以个人认为，英文的几种缩写规则，和中文的造字方法，其实有很多相通之处，这点在化学元素表上最为明显。

**Comment by nobodxbodon** [comment]
@absente 关于英文缩写和中文造字的相通之处, 还望详细阐述. 个人仍然认为, 即便有些英文缩写确有领域内约定俗成的概念, 仍然很难保证跨领域的通用性. [之前PL的例子](https://github.com/program-in-chinese/overview/issues/76#issuecomment-412938105)在这里也适用.

**Comment by absente** [comment]
> 关于英文缩写和中文造字的相通之处, 还望详细阐述.
@nobodxbodon 举个最简单的例子，HTTP, TCP, IP，如果把P当作部首，那么对应的是三个单字。类似的，在化学造字的时候也有考虑分类问题，所以氮氢氧都是气打头

**Comment by absente** [comment]
昨天在v2ex的讨论帖里，为了方便交流，引出了[新文言]的概念，其实也可以用古文编程等价替换：https://www.v2ex.com/t/503773

> 基于中文表达逻辑的编程语言

另外附上一则评论，供参考：

```
just for fun 没问题，只是总有些中文编程布道师，打着国家民族的旗号的，搞些意义不明的事，误人子弟，这种人不狠狠黑一下对不起我一颗真正的爱国心。
你不和这些人划清界限，客观来说躺枪是难免的。
```

**Comment by nobodxbodon** [comment]
> HTTP, TCP, IP，如果把P当作部首，那么对应的是三个单字

首字母缩写和[之前](https://github.com/program-in-chinese/overview/issues/99#issuecomment-431554054)说的缩写不同. P有完整含义而function->fn中的'f','n'没有. 中文命名和英文缩写之间关系请在https://github.com/program-in-chinese/overview/issues/45 继续探讨.

关于"新文言", 看到`所以这个新文言 PL 有没有必要，我自己还没有定论`( https://www.v2ex.com/t/503773#r_6396032 ), 如有实验/进展, 请另开题讨论.

[上面](https://github.com/program-in-chinese/overview/issues/99#issuecomment-435557615)引述的组外言论, 因引用意义不明而易被误会(https://github.com/program-in-chinese/overview/issues/44#issuecomment-435676091).

顶楼的出发点"我觉得为了与易语言这类汉化编程语言区分开来", 不认为应该为了区分而区分. 现在首页和专栏置顶帖都明确了本组内"中文编程"包涵的范围. 如果视而不见者, 只能说装睡的人是叫不醒的.
